### PR TITLE
Fix ActivityListener crash due to concurrent modification

### LINKED ISSUE #2714: Crash in ActivityListener.getActionInProgressOperation()
Reported via Google Play

```
java.lang.NullPointerException: 
  at com.fsck.k9.activity.ActivityListener.getActionInProgressOperation (ActivityListener.java:67)
  at com.fsck.k9.activity.ActivityListener.getOperation (ActivityListener.java:39)
  at com.fsck.k9.activity.Accounts$AccountsHandler.setViewTitle (Accounts.java:161)
  at com.fsck.k9.activity.Accounts$AccountsHandler.access$400 (Accounts.java:150)
  at com.fsck.k9.activity.Accounts$AccountsHandler$1.run (Accounts.java:173)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6692)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
```

https://github.com/k9mail/k-9/blob/cd0f48ba05b4885ea820ef566b135865532366b0/k9mail/src/main/java/com/fsck/k9/activity/ActivityListener.java#L66-L67

~This is super odd. `Account.getInboxFolderName()` should never return `null`. Even if `Account` is modified by another thread during the first and second call to `Account.getInboxFolderName()`.~
It's probably `mAccount` that is set to `null`.

### PR DESCRIPTION
**Pull request by cketti**
`ActivityListener` accesses its field from both background threads and the main thread without locking. That leads to quite a few `NullPointerException`s for our users. This PR adds proper locking.

Fixes #2714

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/activity/ActivityListener.java [hunk 1]
```diff
@@ -1,5 +1,6 @@
 package com.fsck.k9.activity;
 
+
```
Comment (philipwhiuk) [inline k9mail/src/main/java/com/fsck/k9/activity/ActivityListener.java]: Unnecessary new line

Comment (cketti) [reply k9mail/src/main/java/com/fsck/k9/activity/ActivityListener.java]: It was added by Android Studio's "reformat code" action using our code style scheme. Apparently our settings file includes this:

```xml
    <option name="BLANK_LINES_AFTER_PACKAGE" value="2" />
```
