### PR TITLE
Fix empty move or copy

### LINKED ISSUE #3300: crash on call of expungeUids() with empty set of uids
```
java.lang.IllegalArgumentException: expungeUids() must be called with a non-empty set of UIDs
    at com.fsck.k9.mail.store.imap.ImapFolder.expungeUids(ImapFolder.java:1265)
    at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:1873)
    at com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy.execute(MessagingControllerCommands.java:64)
    at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1626)
    at com.fsck.k9.controller.MessagingController$13.run(MessagingController.java:1579)
    at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:203)
    at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
    at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:172)
    at java.lang.Thread.run(Thread.java:764)
```

### PR DESCRIPTION
**Pull request by Valodim**
Fixes #3300. This was causing a lot of IllegalArgumentExceptions, effectively disabling draft sync for a long time (months?) on my debug version.

### CODE REVIEW

File: k9mail/src/test/java/com/fsck/k9/controller/MessagingControllerTest.java [hunk 1]
```diff
@@ -841,6 +844,20 @@ public void synchronizeMailboxSynchronousLegacy_withUnsyncedNewSmallMessage_shou
         assertEquals(FetchProfile.Item.BODY_SANE, fetchProfileCaptor.getAllValues().get(3).get(0));
     }
 
+    @Test
+    public void processPendingMoveOrCopy_withOnlyLocalMessages() throws Exception {
+        configureRemoteStoreWithFolder();
+
+        Collection<String> strings = Arrays.asList(K9.LOCAL_UID_PREFIX + "msg1", K9.LOCAL_UID_PREFIX + "msg2");
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/controller/MessagingControllerTest.java]: Nit: should be `uids` instead of `strings`.

**Comment by Valodim** [comment]
@cketti this one is probably also worth backporting
