### PR TITLE
Reset account settings during setup progression

### LINKED ISSUE #5088: Port isn't changed when switching account types
**Describe the bug**
With PR #5085 merged it's possible to start account setup, but then before finishing the setup go back and change the account type. This will keep the original port number.

**To Reproduce**
1. Go to settings and click "Add account" or use the onboarding flow to add an account
2. Enter email address and password for a domain that needs to be manually configured
3. Select "IMAP"
4. Enter correct server settings and press "Next"
5. Use back button twice to go back to the account type selection screen
6. Select "POP3"
7. Notice that the 'Port' input field still contains the port configured in step 4

**Expected behavior**
Use the default port number for the selected account type.

**Environment (please complete the following information):**
 - K-9 Mail version: 1259d372b6ae7f2f9cfdc5cdbfd373f0a0691d8b

### PR DESCRIPTION
**Pull request by Monkey-Matt**
Fixes #5088 (Port isn't changed when switching account types)
As per my comment on that issue I've made it so that all settings are reset when you navigate to the incoming/outgoing screen. 
Doesn't change what the default settings are when first navigating to those screens just resets back to those same defaults each time you go to the incoming/outgoing screens.

### CODE REVIEW

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt [hunk 1]
```diff
@@ -27,6 +30,9 @@ class AccountSetupAccountType : K9Activity() {
 
     private lateinit var account: Account
     private var makeDefault = false
+    private lateinit var defaultAccountSettings: DefaultAccountSettings
+
+    private val backendManager = get(BackendManager::class.java)
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt:35]: `DI.get()` is a helper that is only required for Java classes. In Kotlin you can write this as

```kotlin
private val backendManager: BackendManager by inject()
```

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt [hunk 2]
```diff
@@ -42,47 +48,60 @@ class AccountSetupAccountType : K9Activity() {
...
-    private fun setupAccount(serverType: String, schemePrefix: String) {
-        setupStoreAndSmtpTransport(serverType, schemePrefix)
+    private fun setupAccount(serverType: String) {
+        setupStoreAndSmtpTransport(serverType)
         createSpecialLocalFolders()
         returnAccountTypeSelectionResult()
     }
 
-    private fun setupStoreAndSmtpTransport(serverType: String, schemePrefix: String) {
+    private fun setupStoreAndSmtpTransport(serverType: String) {
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt:68]: With the introduction of `DefaultAccountSettings` we can now move the store/transport URI creation to `AccountSetupIncoming` and `AccountSetupOutgoing`. We just need to pass the `DefaultAccountSettings` to those activities.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/DefaultAccountSettings.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
+package com.fsck.k9.activity.setup;
+
+import com.fsck.k9.mail.AuthType;
+
+public class DefaultAccountSettings implements java.io.Serializable {
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/DefaultAccountSettings.java:5]: I think something like `BasicAccountSettings` or `InitialAccountSettings` would be a better name.

New code should be written in Kotlin. Instead of `Serializable` we can make this a `Parcelable`.

```kotlin
@Parcelize
data class DefaultAccountSettings(
    val authenticationType: AuthType,
    val email: String,
    val password: String?,
    val clientCertificateAlias: String?
) : Parcelable
```

**Review by cketti — CHANGES_REQUESTED** [review]
I like the approach, but would love to take it a little bit further by passing the new class on to `AccountSetupIncoming` and `AccountSetupOutgoing`.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/DefaultAccountSettings.java (hunk 3 above)
Comment (Monkey-Matt) [reply app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/DefaultAccountSettings.java]: Good call on the name change. I've done that and changed to kotlin as suggested. 

Is the use of `parcelable` over `serializable` a speed issue? (I haven't dug into the comparison before but that's what's my googling suggested)

Potentially related question. Whats the `legacy` file structure that this is in used for? My assumption was it's for java but there is kotlin files in there too.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt (hunk 1 above)
Comment (Monkey-Matt) [reply app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt]: Good spotting, I've made that change now. Thanks

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt (hunk 2 above)
Comment (Monkey-Matt) [reply app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt:66]: The store URI creation is done in `SetupAccountType` instead of `SetupIncoming` because there is no way to know inside `SetupIncoming` if it should be restored to the initial settings. One example is visiting the `SetupIncoming` screen to edit the settings (as opposed to during initial setup) as this screen is used in that scenario also, another is after going back to `SetupAccountType` then into `SetupIncoming` for a second time during setup.
The best method I've found for determining when the initial settings should be restore is when your on the previous step. I.e. if your on `SetupAccountType` it means you can delete any previous incoming settings and restore the initial settings.

The reason the transport URI is also setup in `SetupAccountType` and not differed until `SetupIncoming` is that the account transport URI settings are required in `SetupIncoming` during the connection testing step.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/DefaultAccountSettings.java (hunk 3 above)
Comment (cketti) [reply app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/DefaultAccountSettings.java]: > Is the use of `parcelable` over `serializable` a speed issue? (I haven't dug into the comparison before but that's what's my googling suggested)

It used to be. Not sure if that's still very relevant. Mainly, it's the canonical way of doing things on Android.

> Potentially related question. Whats the `legacy` file structure that this is in used for? My assumption was it's for java but there is kotlin files in there too.

It's part of the name of the Gradle module (`:app:ui:legacy`). Currently it contains all of the UI code. The goal is to split this up into multiple modules, one per feature (or group of closely related features). That will help with compilation avoidance, but could also be useful for custom K-9 Mail versions/forks that don't want to include certain features.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt (hunk 2 above)
Comment (cketti) [reply app/ui/legacy/src/main/java/com/fsck/k9/activity/setup/AccountSetupAccountType.kt:66]: > The store URI creation is done in `SetupAccountType` instead of `SetupIncoming` because there is no way to know inside `SetupIncoming` if it should be restored to the initial settings. One example is visiting the `SetupIncoming` screen to edit the settings (as opposed to during initial setup) as this screen is used in that scenario also, another is after going back to `SetupAccountType` then into `SetupIncoming` for a second time during setup.

The Intent action is different when `AccountSetupIncoming` is started during setup vs. when it is started to edit the current settings. 
When going back in the setup workflow we don't launch a new copy of `AccountSetupIncoming`, we return to the old one. That means the activity is rarely restarted and we don't even hit the code to set initial values. But if the activity is restarted `savedInstanceState` won't be `null`.
Together this information could be used to know when to set the initial account values. But I just had a closer look at `AccountSetupIncoming` and realized it would need a lot more work. Since we want to rewrite the setup code anyway, it's not worth doing much extra work now. So we'll stick with your current approach :+1:

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
I squashed the commits, rebased the branch, and fixed a couple of minor issues.

**Comment by cketti** [comment]
Thanks :+1:

**Comment by Monkey-Matt** [comment]
> I squashed the commits, rebased the branch, and fixed a couple of minor issues.
Legend thanks for doing that cketti
