### PR TITLE
Fix behaviour of summary notifications

### LINKED ISSUE #2121: Erroneous "+0 more" messages on Notifications.
### Expected behavior
Since 5.202 occasionally the notifications can show "+0".  This never as witnessed in 5.200 and before.

### Actual behavior
Notifications will show a "+X" number in the expanded notification where the X is the number of new messages exceeding that of the notification displayed messages.

### Steps to reproduce
Cannot reproduce at will - Ive not actually tried to work out how.  However, see screenshots:

Note it says **6 new messages**, yet only displays 5 and then "**+0** more":

image

image

### Environment
K-9 Mail version: 5.203

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

### PR DESCRIPTION
**Pull request by philipwhiuk**
This should fix #2121

### CODE REVIEW

File: k9mail/src/test/java/com/fsck/k9/notification/NotificationDataTest.java [hunk 1]
```diff
@@ -267,6 +267,32 @@ public void testGetAllMessageReferences() throws Exception {
         assertEquals(messageReference8, messageReferences.get(8));
     }
 
+    @Test
+    public void testOverflowNotifications() {
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/notification/NotificationDataTest.java]: There's an `if` statement in `getSummaryOverflowMessagesCount()`. To properly test that code there should be at least two tests.

Comment (philipwhiuk) [inline k9mail/src/test/java/com/fsck/k9/notification/NotificationDataTest.java]: I'll submit a PR for this missing test this weekend
