### PR TITLE
fix: correctly handles the server ID when an IMAP prefix is present, ensuring the prefix is not duplicated

### LINKED ISSUE #9567: Folders on IMAP servers with prefixes are completely broken since 12.0b4
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.0b4, 12.0b5

### Where did you get the app from?

Other

### Android version

13 (xiaomi.eu 14.0.3.0.TJUMIXM)

### Device model

Xiaomi POCO X3 Pro (global)

### Steps to reproduce

Requires an IMAP mail server that uses prefix for non-INBOX mailboxes (e.g. GMail - #9616).

#### Variant 1 - fetching folder

1. Fetch list of folders
2. Open any folder other than _Inbox_ (e.g. _Spam_ - `INBOX.Spam`)
3. Load messages/refresh

#### Variant 2 - deleting messages

1. Make sure that there is a trash folder (e.g. `INBOX.Trash`)
2. Delete a message from inbox

#### Variant 1 - fetching folder

Messages from the selected folder are fetched from server (e.g. using command `EXAMINE "INBOX.Spam"`) and displayed.

#### Variant 2 - deleting messages

Deleted message is moved to the trash folder.

#### Variant 1 - fetching folder

Command `EXAMINE "INBOX.INBOX.Spam"` is sent and obviously fails, because there is no such folder.

#### Variant 2 - deleting messages

Command similar to `UID MOVE 27707:27708,27714:27715 "INBOX.INBOX.Trash"` (here I was deleting multiple messages) is sent and also fails. This leads to a desync, because messages end up in the local trash, disappearing from inbox, but still exist on server and are shown to other clients.

I was wondering why desktop Thunderbird and webmail showed 15 more unread messages than Thunderbird for Android and thought it is a weird sync problem.

### Regression analysis

This regression is caused by #9241 that was uplifted to beta in #9523 (I guess now some of the associated risk is known) and released in 12.0b4.

`serverId` is _absolute_ - it includes folder name including the prefix. Previously most folder `serverId`s were "old server IDs" and [had the prefix removed](https://github.com/thunderbird/thunderbird-android/commit/74cbed1bdb1375cb15014b16cd75463b48f60071#diff-b88fcb0b0a4fbe9cda33c13ffc19bf81f7bc110a545cf81e24c87532fdef03b5L193-L203). Now folders are initialised with `serverId` that contains prefix, but commands either use `encodedName` which is just [`folderNameCodec.encode(prefixedName)`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L98-L102) or directly call `folderNameCodec.encode(folder.prefixedName)` ([`copyMessages`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L309-L310) and [`moveMessagesUsingMoveExtension`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L345-L346)) - in either case [`prefixedName`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L73-L96) is used and [`prefixedName`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L73-L96) prefixes the `serverId` (that already has prefix).

### Logs

<details>
<summary>
Logs showing refreshing folders list (<code>LIST</code> command) and an attempt at fetching spam folder content (<code>EXAMINE</code>)
</summary>

```log
08-04 23:19:05.601 23247  7026 I MessagingController: Running command 'refreshFolderList', seq = 33 (foreground priority)
08-04 23:19:05.609 23247  7026 V RealImapConnection: conn9763719>>> 5 NOOP
08-04 23:19:05.677 23247  7026 V ImapResponseParser: conn9763719<<<#5# [OK, NOOP completed.]
08-04 23:19:05.690 23247  7026 V RealImapConnection: conn9763719>>> 6 LIST "" "INBOX.*" RETURN (SPECIAL-USE)
08-04 23:19:05.703 23247 23247 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 23:19:05.715 23247 23247 I HandWritingStubImpl: refreshLastKeyboardType: 1
08-04 23:19:05.715 23247 23247 I HandWritingStubImpl: getCurrentKeyboardType: 1
08-04 23:19:05.768 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Drafts], ., INBOX.Drafts]
08-04 23:19:05.785 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Junk], ., INBOX.Spam]
08-04 23:19:05.800 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Sent], ., INBOX.Sent Items]
08-04 23:19:05.814 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Trash], ., INBOX.Trash]
08-04 23:19:05.828 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [], ., INBOX.Templates]
08-04 23:19:05.837 23247  7026 V ImapResponseParser: conn9763719<<<#6# [OK, List completed.]
08-04 23:19:05.930 23247  7026 I K9StorageEditor: Committing preference changes
08-04 23:19:05.987 23247  7027 D OpenGLRenderer: endAllActiveAnimators on 0xb4000079135b5000 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000798156a080
08-04 23:19:05.999 23247  7026 I K9StorageEditor: Preferences commit took 68 ms
08-04 23:19:06.058 23247  7030 V PushController: PushController.updatePushers()
08-04 23:19:06.124 23247  7026 I K9StorageEditor: Committing preference changes
08-04 23:19:06.178 23247  7026 I K9StorageEditor: Preferences commit took 57 ms
08-04 23:19:06.232 23247  7026 D MessagingController: Folder list successfully refreshed @ Mon Aug 04 23:19:06 CEST 2025
08-04 23:19:06.241 23247  7030 V PushController: ..Running PushControllers: [0308d0e4-7659-46d8-befe-ec78911c1b7d]
08-04 23:19:06.269 23247  7026 I K9StorageEditor: Committing preference changes
08-04 23:19:06.350 23247  7026 I K9StorageEditor: Preferences commit took 81 ms
08-04 23:19:06.390 23247  7026 I MessagingController:  Command 'refreshFolderList' completed
08-04 23:19:06.411 23247  7030 V PushServiceManager: PushServiceManager.start()
08-04 23:19:06.419 23247  7030 V PushServiceManager: ..PushService already running
08-04 23:19:06.426 23247  7030 V BootCompleteManager: Enable BootCompleteReceiver
08-04 23:19:06.436 23247  7030 V PushController: PushController.updatePushers()
08-04 23:19:06.447 23247  7030 V PushController: ..Running PushControllers: [0308d0e4-7659-46d8-befe-ec78911c1b7d]
08-04 23:19:06.465 23247  7030 V PushServiceManager: PushServiceManager.start()
08-04 23:19:06.468 23247  7030 V PushServiceManager: ..PushService already running
08-04 23:19:06.471 23247  7030 V BootCompleteManager: Enable BootCompleteReceiver
08-04 23:19:06.477 23247  7030 V PushController: PushController.updatePushers()
08-04 23:19:06.483 23247  7030 V PushController: ..Running PushControllers: [0308d0e4-7659-46d8-befe-ec78911c1b7d]
08-04 23:19:06.493 23247  7030 V PushServiceManager: PushServiceManager.start()
08-04 23:19:06.496 23247  7030 V PushServiceManager: ..PushService already running
08-04 23:19:06.500 23247  7030 V BootCompleteManager: Enable BootCompleteReceiver
08-04 23:19:07.987 23247 23247 D MIUIInput: [KeyEvent] ViewRootImpl windowName 'net.thunderbird.android.debug/com.fsck.k9.ui.managefolders.ManageFoldersActivity', KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=90282514000000, downTime=90282514000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=23:19:07.891
08-04 23:19:08.008 23247 23247 D MIUIInput: [KeyEvent] ViewRootImpl windowName 'net.thunderbird.android.debug/com.fsck.k9.ui.managefolders.ManageFoldersActivity', KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=90282571000000, downTime=90282514000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=23:19:07.948
08-04 23:19:08.180 23247  7026 I MessagingController: Running command 'clearNotifications', seq = 34 (foreground priority)
08-04 23:19:08.191 23247  7026 V NotificationController: Removing some notifications for account 0308d0e4-7659-46d8-befe-ec78911c1b7d
08-04 23:19:08.195 23247 23247 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 23:19:08.199 23247  7026 I MessagingController:  Command 'clearNotifications' completed
08-04 23:19:08.279 23247 23247 D VRI[MessageList]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:2957 android.view.ViewRootImpl.doTraversal:36 android.view.ViewRootImpl$TraversalRunnable.run:7 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:20
08-04 23:19:08.280 23247 23247 D VRI[MessageList]: vri.Setup new sync id=7 syncSeqId=0
08-04 23:19:08.469 23247 23247 D VRI[MessageList]: vri.reportDrawFinished syncSeqId=0 android.view.ViewRootImpl.lambda$createSyncIfNeeded$4$android-view-ViewRootImpl:5 android.view.ViewRootImpl$$ExternalSyntheticLambda1.run:6 android.os.Handler.handleCallback:2 android.os.Handler.dispatchMessage:4 android.os.Looper.loopOnce:182
08-04 23:19:08.544 23247 23247 D MessageListViewModel: Received new MessageListInfo: MessageListInfo(messageListItems=[], hasMoreMessages=true)
08-04 23:19:08.546 23247 23247 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 23:19:08.559 23247 23247 I HandWritingStubImpl: refreshLastKeyboardType: 1
08-04 23:19:08.559 23247 23247 I HandWritingStubImpl: getCurrentKeyboardType: 1
08-04 23:19:10.953 23247  7026 I MessagingController: Running command 'loadMoreMessages', seq = 35 (background priority)
08-04 23:19:10.974 23247  7026 D MessagingController: Last folder list refresh @ Mon Aug 04 23:19:06 CEST 2025. Not refreshing now.
08-04 23:19:10.992 23247  7026 I ImapSync: Synchronizing folder konto.pl:INBOX.Spam
08-04 23:19:10.998 23247  7026 V ImapSync: SYNC: About to get local folder INBOX.Spam
08-04 23:19:11.012 23247  7026 V ImapSync: SYNC: About to get remote folder INBOX.Spam
08-04 23:19:11.019 23247  7026 V ImapSync: SYNC: About to open remote folder INBOX.Spam
08-04 23:19:11.028 23247  7026 V RealImapConnection: conn9763719>>> 7 NOOP
08-04 23:19:11.119 23247  7026 V ImapResponseParser: conn9763719<<<#7# [OK, NOOP completed.]
08-04 23:19:11.131 23247  7026 V RealImapConnection: conn9763719>>> 8 EXAMINE "INBOX.INBOX.Spam"
08-04 23:19:11.201 23247  7026 V ImapResponseParser: conn9763719<<<#8# [NO, Mailbox doesn't exist: INBOX.INBOX.Spam]
08-04 23:19:11.221 23247  7026 E RealImapFolder: Unable to open connection for 0308d0e4-7659-46d8-befe-ec78911c1b7d:INBOX.Spam/MessagingController/conn9763719
08-04 23:19:11.221 23247  7026 E RealImapFolder: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE "INBOX.INBOX.Spam"; response: #8# [NO, Mailbox doesn't exist: INBOX.INBOX.Spam]
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:127)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:747)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:733)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:106)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:146)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:117)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:84)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:56)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:658)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:596)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.loadMoreMessagesSynchronous(MessagingController.java:560)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.lambda$loadMoreMessages$4$com-fsck-k9-controller-MessagingController(MessagingController.java:544)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:239)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(Unknown Source:0)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:179)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at java.lang.Thread.run(Thread.java:1012)
08-04 23:19:11.236 23247  7026 E ImapSync: synchronizeMailbox
08-04 23:19:11.236 23247  7026 E ImapSync: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE "INBOX.INBOX.Spam"; response: #8# [NO, Mailbox doesn't exist: INBOX.INBOX.Spam]
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:127)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:747)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:733)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:106)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:146)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:117)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:84)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:56)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:658)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:596)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.loadMoreMessagesSynchronous(MessagingController.java:560)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.lambda$loadMoreMessages$4$com-fsck-k9-controller-MessagingController(MessagingController.java:544)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:239)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(Unknown Source:0)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:179)
08-04 23:19:11.236 23247  7026 E ImapSync:      at java.lang.Thread.run(Thread.java:1012)
08-04 23:19:11.259 23247  7026 E ImapSync: Failed synchronizing folder konto.pl:INBOX.Spam @ Mon Aug 04 23:19:11 CEST 2025
08-04 23:19:11.267 23247  7026 I MessagingController:  Command 'loadMoreMessages' completed
```

</details>

<details>
<summary>
Logs showing failed message removal (moving to trash)
</summary>

```
08-04 21:02:52.606 22513 31526 V RealImapConnection: conn83236368>>> 191 UID MOVE 27707:27708,27714:27715 "INBOX.INBOX.Trash"
08-04 21:02:52.653 22513 31526 V ImapResponseParser: conn83236368<<<#191# [NO, [TRYCREATE], Mailbox doesn't exist: INBOX.INBOX.Trash]
08-04 21:02:52.655 22513 31526 E MessagingController: Failure of command 'move_and_mark_as_read' was permanent, removing command from queue
08-04 21:02:52.655 22513 31526 E MessagingController: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID MOVE 27707:27708,27714:27715 "INBOX.INBOX.Trash"; response: #191# [NO, [TRYCREATE], Mailbox doesn't exist: INBOX.INBOX.Trash]
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:127)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:747)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:733)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeCommandWithIdSet(RealImapConnection.kt:770)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.moveMessagesUsingMoveExtension(RealImapFolder.kt:350)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.moveMessages(RealImapFolder.kt:335)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveOrCopyMessages(CommandMoveOrCopyMessages.kt:59)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveMessages(CommandMoveOrCopyMessages.kt:15)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.moveMessagesAndMarkAsRead(ImapBackend.kt:104)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:932)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.processPendingMoveAndRead(MessagingController.java:902)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingControllerCommands$PendingMoveAndMarkAsRead.execute(MessagingControllerCommands.java:94)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:752)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController$3.run(MessagingController.java:722)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:239)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:179)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at java.lang.Thread.run(Thread.java:1012)
```

</details>

### LINKED ISSUE #9771: Special folders gets wiped out when updating from 11.x to 12.x
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.1

### Where did you get the app from?

Google Play

### Android version

16

### Device model

Pixel 8

### Steps to reproduce

Upgrade Thunderbird Mobile to 12.1 with Play store. After that open app and check folders:
- The "Unified inbox" only contains messages from Imap's INBOX folder, and no other messages from folders which were added to be shown in unified inbox.
- If you select a folder and refresh it, no messages appear
- In the account's settings under "folders", all "standard" folders (Trash, Sent, Drafts, Archives,...)  disappeared and have not selected any IMAP folder on server side. They can be selected again by clicking on them, but this does also not fix the issue
- If you send a mail, the mail does not appear in Sent folder anymore (not even server side).

The important information about Server: Dovecot Mail server with "dotted" folder name. "INBOX" is Root folder, and all folders below are named "INBOX.Sent", "INBOX.Trash",....

They still appear correctly in the UI, also after refresh, but basically all folders are unreachable.

The mail server does not show any messages about non-existant folders, will enable debug logging there.

### Expected behavior

After upgrade the folders which appear in the UI should contain messages.

### Actual behavior

All folders are empty and syncing them does not refresh them.

### Logs

The above "retrieve logs" documentation is not available so I have no idea how to get logs!

### PR DESCRIPTION
**Pull request by rafaeltonholo**
Fixes #9567.
Fixes #9771.

### Pre-requisites
To test the following changes, you need to have:
- An email from an email provider which DOES enforce IMAP prefixes (returned via `NAMESPACE` command; Email providers that use the dovecot IMAP Servers are good ones to use)
- An email from an email provider which DOES NOT enforce IMAP prefixes (Google, Outlook, Yahoo, etc)

#### Steps to Reproduce
1. Delete the app if you have it installed
2. `git checkout 70b3dc3b41650a13a7ed9a1933377513afe8a3da`
3. Sync, build and install the app
4. Set up the account that uses the IMAP prefix
5. Close the app
6. Checks out this branch
7. Sync, build and install the app
8. Open the app, try to synchronize any folder that is not the INBOX folder.

#### Expected
The app should be able to download the messages.

#### Steps to Reproduce
1. Delete the app if you have it installed
2. `git checkout 70b3dc3b41650a13a7ed9a1933377513afe8a3da`
3. Sync, build and install the app
4. Set up the account that uses the IMAP prefix
5. Set up the special folders, setting any folder you want
6. Close the app
6. Checks out this branch
7. Sync, build and install the app
8. Open the Account Drawer
9. Tap on "Manage folders"
10. Tap on the Overflow button (Three dots, top right)
11. Tap on "Refresh folder list"

#### Expected
The folders must keep their assignment (Drafts, Archive, etc), unless there was a change on the server side.

### CODE REVIEW

File: legacy/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo90.kt
Comment (wmontwe) [inline legacy/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo90.kt:1]: The test to very the migration is missing, i added a ticket to keep track #9789.

File: mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/RealImapFolderTest.kt [hunk 1]
```diff
@@ -1622,29 +1728,32 @@ class RealImapFolderTest {
 
     private fun createMessageRetrievalListener() = mock<MessageRetrievalListener<ImapMessage>>()
 
-    private fun prepareImapFolderForOpen(openMode: OpenMode) {
-        val imapResponses = listOf(
-            createImapResponse("* FLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft NonJunk \$MDNSent)"),
```
Comment (wmontwe) [inline mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/RealImapFolderTest.kt:1627]: Why was this line removed?

**Comment by woneill** [comment]
Can/should this be added to the Thunderbird 13 milestone? Waiting for two full release for a significant bug fix doesn't feel good.

File: mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/RealImapFolderTest.kt (hunk 1 above)
Comment (rafaeltonholo) [reply mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/RealImapFolderTest.kt:1627]: `prepareImapFolderForOpen` was not removed, but split into two methods, where one builds the list of responses (`createOpenImapResponse`) and another sets up the list of responses as an answer to a command (`prepareImapFolderForOpen`).

**Comment by woneill** [comment]
> Can/should this be added to the Thunderbird 13 milestone? Waiting for two full release for a significant bug fix doesn't feel good.

Confirmed this is working in the 13.0.b2 release. Thanks for the uplift @wmontwe !
