### PR TITLE
Don't load recipients with no email (fixes #2973)

### LINKED ISSUE #2973: Crashes on adding an address to a reply list
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

I believe this is the same as "App crashed by typing address in the address field when composing a message #1251" except that bug was not fixed for when you reply to a message.

### Expected behavior
Should auto-complete the address and not crash

### Actual behavior
Crashes on the second character typed

### Steps to reproduce
1. Tap the left double-arrow at the bottom while viewing a message (to reply or forward)
2. Tap Reply
3. Tap in the To field after any existing addresses
4. Type in the first characters of an address to send to

### Environment
K-9 Mail version: 5.208

Android version: 7.0
[logcat.txt](https://github.com/k9mail/k-9/files/1565095/logcat.txt)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by philipwhiuk**
Skip contacts with no email when trying to add them.

* Unit test for loading contact
* Unit test for trying to load contact with no email
* New `NotNull` annotations on various classes to try and discourage bad API usage.

Fixes #2973

### CODE REVIEW

File: k9mail-library/src/main/java/com/fsck/k9/mail/Address.java [hunk 1]
```diff
@@ -32,20 +33,20 @@
 
     private String mPersonal;
 
-    public Address(Address address) {
+    public Address(@NonNull Address address) {
```
Comment (cketti) [inline k9mail-library/src/main/java/com/fsck/k9/mail/Address.java]: I don't like adding `@NonNull` annotations because it should be the default. Rather add `@Nullable` when `null` is a valid option.

File: k9mail/src/main/java/com/fsck/k9/activity/compose/RecipientLoader.java [hunk 2]
```diff
@@ -374,13 +374,15 @@ private void fillContactDataFromCursor(Cursor cursor, List<Recipient> recipients
...
             }
 
-            Recipient recipient = new Recipient(name, email, addressLabel, contactId, lookupKey);
-            if (recipient.isValidEmailAddress()) {
-                Uri photoUri = cursor.isNull(INDEX_PHOTO_URI) ? null : Uri.parse(cursor.getString(INDEX_PHOTO_URI));
-
-                recipient.photoThumbnailUri = photoUri;
-                recipientMap.put(email, recipient);
-                recipients.add(recipient);
+            if (email != null) {
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/activity/compose/RecipientLoader.java]: We could bail out earlier by changing the check further up to…

```java
if (email == null || recipientMap.containsKey(email)) {
    continue;
}
```

File: k9mail/src/test/java/com/fsck/k9/activity/compose/RecipientLoaderTest.java [hunk 3]
```diff
@@ -141,4 +162,41 @@ private void setupCryptoProviderStatus(Address address, String uidStatus, String
...
+
+        List<Recipient> recipients = recipientLoader.loadInBackground();
+
+        assertEquals(1, recipients.size());
+        assertEquals("bob@host.com", recipients.get(0).address.getAddress());
+        assertEquals(RecipientCryptoStatus.UNAVAILABLE, recipients.get(0).getCryptoStatus());
+    }
+
+    @Test
+    public void queryContactProvider_ignoresRecipientWithNoEmaill() throws Exception {
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/activity/compose/RecipientLoaderTest.java]: Typo: "Emaill"

File: k9mail-library/src/main/java/com/fsck/k9/mail/Address.java (hunk 1 above)
Comment (philipwhiuk) [reply k9mail-library/src/main/java/com/fsck/k9/mail/Address.java]: I find `@NonNull`ing somewhat non obvious non-null's is more useful than getting caught up in ideals, but I'll remove it.
