### PR TITLE
Fix placement of action mode bar

### LINKED ISSUE #3832: Action mode bar is displayed above toolbar
### Expected behavior
When selecting emails, the action mode should overlay the toolbar

### Actual behavior
The action mode is added above the toolbar

### Steps to reproduce
1. Select mail

### Environment
K-9 Mail version: master

### Possible fix

https://stackoverflow.com/q/26483778/4193263

screenshot_20181218-183439_k-9_mail-picsay

### PR DESCRIPTION
**Pull request by cketti**
Fixes #3832

### CODE REVIEW

File: app/ui/src/main/java/com/fsck/k9/fragment/MessageListFragment.java [hunk 1]
```diff
@@ -2693,8 +2694,12 @@ private void resetActionMode() {
     }
 
     private void startAndPrepareActionMode() {
-        actionMode = getActivity().startActionMode(actionModeCallback);
-        actionMode.invalidate();
+        AppCompatActivity activity = (AppCompatActivity) requireActivity();
+        ActionMode actionMode = activity.startSupportActionMode(actionModeCallback);
```
Comment (wiktor-k) [inline app/ui/src/main/java/com/fsck/k9/fragment/MessageListFragment.java]: Is there a reason you use `actionMode` local & also assign to the `actionMode` field instead of just using the field (like the previous code)? (performance reasons?)

**Comment by wiktor-k** [comment]
Looks and works like a charm on my device :+1:

File: app/ui/src/main/java/com/fsck/k9/fragment/MessageListFragment.java (hunk 1 above)
Comment (wiktor-k) [reply app/ui/src/main/java/com/fsck/k9/fragment/MessageListFragment.java]: > Also, writing a non-null value to and then immediately reading from a field isn't guaranteed to get you a non-null value, because concurrent modifications are possible.

I would rather expect the opposite - that writing to this field from another thread would *not* be visible as `actionMode` is not volatile and there are no explicit barriers here (no `synchronized`, AtomicReference etc.)

Thanks for the explanation! I think it's good to be merged.
