### PR TITLE
Properly handle exceptions thrown by ImapResponseCallback

### LINKED ISSUE #1919: ImapResponseParser.parseLiteral timeout error
[k9-log.txt](https://github.com/k9mail/k-9/files/681130/k9-log.txt)
### Expected behavior
Tell us what should happen
K9 should be able to read IMAP mail
### Actual behavior
Tell us what happens instead
It logs in the IMAP account but doesn't read the mail box.
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.201
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

### PR DESCRIPTION
**Pull request by cketti**
Fixes #1919

### CODE REVIEW

File: k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java [hunk 1]
```diff
@@ -354,26 +354,32 @@ private Object parseLiteral() throws IOException {
...
                 }
+
+                fixed.skipRemaining();
             }
 
+            if (callbackException != null) {
+                if (exception == null) {
+                    exception = callbackException;
+                }
+                return "EXCEPTION";
```
Comment (philipwhiuk) [inline k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java]: This is horrible, firstly because EXCEPTION could technically be a valid response. 

And you never test this behaviour or even use this magic value to see whether `exception` should be checked.

I'm not going to reject the changes, but at the least we should track this monstrosity and refactor it in the future

Comment (cketti) [inline k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java]: It's just for debugging purposes. When there was an exception the `ImapResponse` instance is never returned to the caller.

Comment (philipwhiuk) [inline k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java]: Hmm fine. It still feels ugly.
