### PR TITLE
fix: build warnings

### LINKED ISSUE #10600: Reduce build warnings
When building the project we have a lot of warnings. We should reduce these to not be distracted while working on the project.

#### 1. Kotlin Compiler Warnings

* [x] Suppress or address `expect`/`actual` classes Beta warning in `core:logging:config` using `-Xexpect-actual-classes`.
* [x] Fix 'internal' declaration exposing 'public/*package*/' type warnings (becoming error in Kotlin 2.4):
  * [x] `mail:protocols:imap` (`ImapResponseCallback`, `ImapList`).
  * [x] `legacy:core` (`StringSetting`, `SettingsDescription`).
  * [x] `legacy:crypto-openpgp` (`EncryptionDetector`).
* [x] Address 'Type argument for reified type parameter was inferred to intersection type' in `legacy:storage` (`K9NotificationStore.kt`).

#### 2. Deprecation Fixes

* [x] Update `ThemeColorScheme.kt` to use the new `ColorScheme` constructor with 'fixed' container roles.
* [x] Update `IncomingFormItems.kt` and `OutgoingFormItems.kt` to use the new `KeyboardOptions` constructor.
* [x] Replace `TabRow` with `PrimaryTabRow`/`SecondaryTabRow` in `app-ui-catalog`.
* [x] Update `TextFieldOutlinedSelect.kt` to use `ExposedDropdownMenuAnchorType`.

#### 3. Legacy Code Deprecations

* [x] Replace `ProgressDialog` usages in `ProgressDialogFragment.kt`.
* [x] Resolve deprecations and warnings in `ItemTouchHelper`
* [x] Resolve deprecations and warnings in `LinearLayoutManager`

#### 4. Build Infrastructure & Tooling

* [x] Investigate/Silence "Unable to strip" warnings for native libraries (e.g., `libandroidx.graphics.path.so`).

#### 5. Java Compiler Warnings

* [x] Address `[dep-ann]` warnings in generated AIDL code (`IOpenPgpService.java`).

### PR DESCRIPTION
**Pull request by wmontwe**
Resolves #10600

The deprecation warnings in `LinearLayoutManager` and `ItemTouchHelper` have been resolved, and since the message list will be rewritten, these components should no longer be necessary once that rewrite is complete. To minimize noise, I've removed all functionality that is currently unused.

### CODE REVIEW

File: ui-utils/linear-layout-manager/src/main/java/app/k9mail/ui/utils/linearlayoutmanager/LinearLayoutManager.java [hunk 1]
```diff
@@ -1820,38 +1617,32 @@ private View getChildClosestToEnd() {
...
         if (mShouldReverseLayout) {
-            return findOneVisibleChild(0, getChildCount(), completelyVisible,
-                    acceptPartiallyVisible);
+            return findOneVisibleChild(0, getChildCount(), false,
+                true);
         } else {
-            return findOneVisibleChild(getChildCount() - 1, -1, completelyVisible,
-                    acceptPartiallyVisible);
+            return findOneVisibleChild(getChildCount() - 1, -1, false,
+                true);
```
Comment (rafaeltonholo) [inline ui-utils/linear-layout-manager/src/main/java/app/k9mail/ui/utils/linearlayoutmanager/LinearLayoutManager.java:1645]: I would keep the `!mSmoothScrollbarEnabled` for clarity here:
```suggestion
            return findOneVisibleChild(0, getChildCount(), !mSmoothScrollbarEnabled,
                true);
} else {
            return findOneVisibleChild(getChildCount() - 1, -1, !mSmoothScrollbarEnabled,
                true);
```

File: ui-utils/linear-layout-manager/src/main/java/app/k9mail/ui/utils/linearlayoutmanager/LinearLayoutManager.java [hunk 2]
```diff
@@ -1820,38 +1617,32 @@ private View getChildClosestToEnd() {
...
         if (mShouldReverseLayout) {
-            return findOneVisibleChild(getChildCount() - 1, -1, completelyVisible,
-                    acceptPartiallyVisible);
+            return findOneVisibleChild(getChildCount() - 1, -1, false,
+                true);
         } else {
-            return findOneVisibleChild(0, getChildCount(), completelyVisible,
-                    acceptPartiallyVisible);
+            return findOneVisibleChild(0, getChildCount(), false,
+                true);
```
Comment (rafaeltonholo) [inline ui-utils/linear-layout-manager/src/main/java/app/k9mail/ui/utils/linearlayoutmanager/LinearLayoutManager.java:1630]: Same as https://github.com/thunderbird/thunderbird-android/pull/10601/changes#r2879709097

**Review by rafaeltonholo — APPROVED** [review]
LGTM. I've left just two comments, but feel free to merge without addressing them.

File: ui-utils/linear-layout-manager/src/main/java/app/k9mail/ui/utils/linearlayoutmanager/LinearLayoutManager.java (hunk 1 above)
Comment (wmontwe) [reply ui-utils/linear-layout-manager/src/main/java/app/k9mail/ui/utils/linearlayoutmanager/LinearLayoutManager.java:1645]: I expect no major changes anymore and after removing all unused methods, the values where always false and true, so I inlined the values.
