### PR TITLE
Don't crash when restoring AccountSettings state

### LINKED ISSUE #3289: selecting key from openkeychain fails
k-9 does not accept the cryptographic key from openkeychain.

The key has been created newly by openkeychain using plain defaults from the
wizzard, except for uploading to the internet being off (as these are tests
yet only).

Steps in detail:

In k-9, after selecting the key from the list, the app takes a short breath
for about 1 sec. and then simply behaves as if it was newly started. Looks
like a quick app restart after a crash or so (but there is no crash message).
When entering the menu Cryptography / My key, there is still "no key
selected".

Tried with K-9/OpenKeyChain 5.502/4.9.2 as well as 5.403/4.9.

Android version: 7.1.2 / LineageOS. Security options were off for both
for both apps.

### PR DESCRIPTION
**Pull request by cketti**
This fixes two bugs in OpenPgpKeyPreference related to saving/restoring state.

Fixes #3289

### CODE REVIEW

File: plugins/openpgp-api-lib/openpgp-api/src/main/java/org/openintents/openpgp/util/OpenPgpKeyPreference.java [hunk 1]
```diff
@@ -73,6 +73,15 @@ public void setDefaultUserId(String userId) {
 
     @Override
     protected void onClick() {
+        bindServiceAndGetSignKeyId(new Intent());
+    }
+
+    private void bindServiceAndGetSignKeyId(final Intent data) {
+        if (mServiceConnection != null) {
```
Comment (Valodim) [inline plugins/openpgp-api-lib/openpgp-api/src/main/java/org/openintents/openpgp/util/OpenPgpKeyPreference.java]: maybe throw in `&& mServiceConnection.isBound()`, there are cases where the connection might die
