### PR TITLE
Request post AUTH capabilities when not provided with them

### LINKED ISSUE #2431: Request post-auth capabilities if not provided them in the OK AUTH response
### Expected behavior
Emails are pushed to my phone, because the IMAP server supports it.

### Actual behavior
Emails aren't pushed to my phone.

When I connect with openssl I see the following:

```
openssl s_client -crlf -connect imap.uni-stuttgart.de:993
* OK [CAPABILITY IMAP4 IMAP4REV1 LITERAL+] perdition ready on mail-proxy.tik.uni-stuttgart.de 00029957
a login ******** *************************
a OK You are so in
a capability
* CAPABILITY IMAP4rev1 LITERAL+ CHILDREN XAOL-OPTION NAMESPACE QUOTA IDLE
a OK CAPABILITY Completed
```

The perdition proxy does not announce IDLE, but after login the capability is announced. Does K9 check for capabilites after login?

### Steps to reproduce
1. Add email account from imap.uni-stuttgart.de
2. Don't receive emails via push

### Environment
K-9 Mail version: 5.206
Android version: 7.1.1
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by philipwhiuk**
Fixes #2431

### CODE REVIEW

File: k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java [hunk 1]
```diff
@@ -327,103 +340,97 @@ private void startTLS() throws IOException, MessagingException, GeneralSecurityE
     }
 
     @SuppressWarnings("EnumSwitchStatementWhichMissesCases")
```
Comment (Valodim) [inline k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java]: can drop this, there's a default

File: k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java [hunk 2]
```diff
@@ -326,104 +339,97 @@ private void startTLS() throws IOException, MessagingException, GeneralSecurityE
...
+                return handlePermanentXoauth2Failure(e);
             } else {
-                handleTemporaryXoauth2Failure(e);
+                return handleTemporaryXoauth2Failure(e);
             }
         }
     }
 
-    private void handlePermanentXoauth2Failure(NegativeImapResponseException e) throws AuthenticationFailedException {
+    private List<ImapResponse> handlePermanentXoauth2Failure(NegativeImapResponseException e) throws AuthenticationFailedException {
```
Comment (cketti) [inline k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java]: This feels weird. Maybe make it return `AuthenticationFailedException`, rename to `permanentXoauth2Failure` and change the call sites to

```java
throw permanentXoauth2Failure(…);
```

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 3]
```diff
@@ -75,17 +75,37 @@ public void setUp() throws Exception {
...
         MockImapServer server = new MockImapServer();
         server.output("* OK [CAPABILITY IMAP4 IMAP4REV1 AUTH=PLAIN]");
         server.expect("1 AUTHENTICATE PLAIN");
         server.output("+");
         server.expect(ByteString.encodeUtf8("\000" + USERNAME + "\000" + PASSWORD).base64());
         server.output("1 OK Success");
-        server.expect("2 LIST \"\" \"\"");
-        server.output("* LIST () \"/\" foo/bar");
-        server.output("2 OK");
+        simplePostAuthenticationDialog(server, true, 2);
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: From reading just this line I have no idea what the second and third argument are for. Maybe have two different methods for each value of the boolean argument. And include something about the integer argument in the method name, e.g. `simplePostAuthenticationDialogStartingWithTag()`

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 4]
```diff
@@ -103,7 +123,7 @@ public void open_authPlain() throws Exception {
         server.output("+");
         server.expect(ByteString.encodeUtf8("\000" + USERNAME + "\000" + PASSWORD).base64());
         server.output("2 OK Success");
-        simplePostAuthenticationDialog(server);
+        simplePostAuthenticationDialog(server, true);
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Same here. The `true` should probably be encoded in the method name.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 5]
```diff
@@ -632,11 +715,11 @@ public void open_withNegativeResponseToStartTlsCommand_shouldThrow() throws Exce
     public void open_withCompressDeflateCapability_shouldEnableCompression() throws Exception {
         settings.setUseCompression(true);
         MockImapServer server = new MockImapServer();
-        simplePreAuthAndLoginDialog(server, "COMPRESS=DEFLATE");
+        simplePreAuthAndLoginDialog(server, "", "COMPRESS=DEFLATE");
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Please introduce a new method rather than adding a new argument that is the same non-obvious value almost everywhere.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 6]
```diff
@@ -856,27 +939,36 @@ private void preAuthenticationDialog(MockImapServer server, String capabilities)
...
+        simplePostAuthenticationDialog(server, requestCapabilities, 3);
     }
 
-    private void simplePostAuthenticationDialog(MockImapServer server, String tag) {
-        server.expect(tag + " LIST \"\" \"\"");
-        server.output("* LIST () \"/\" foo/bar");
-        server.output(tag + " OK");
+    private void simplePostAuthenticationDialog(MockImapServer server, boolean requestCapabilities, int tag) {
+        if (requestCapabilities) {
+            server.expect(tag+" CAPABILITY");
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Code style: A couple of missing spaces in this method.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java (hunk 3 above)
Comment (philipwhiuk) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: This seems like it just breeds method explosion to work around the lack of named arguments in Java.

Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Still, I want the tests to be easy to read, also on GitHub. Having a ton of helper methods at the end of the test file is not something I care about.
