### PR TITLE
fix: display Settings reset/mix up when toggling "Colorize contact pictures"

### LINKED ISSUE #9630: Display Settings reset/mix up when toggling "Colorize contact pictures"
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.0b7

### Where did you get the app from?

Other

### Android version

15

### Device model

Samsung Galaxy S23

### Steps to reproduce

1. Open the Thunderbird app
2. Go to **Settings** → **Display Settings**
3. Unselect Colorize contact pictures
4. Go back to the inbox
5. Return to Settings → **Display Settings**

Image
Image

### Expected behavior

- Colorize contact pictures should remain _unselected_
- Show contact names should stay _selected_ (unchanged)

### Actual behavior

- **Colorize contact pictures** has been re-enabled
- **Show contact names** has been _automatically unselected_, even though it was never changed by the user

Image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by shamim-emon**
- Fixes #9630 
### 🐛 Root Cause of the Bug
 - All Message List–related display settings were not being loaded from PreferenceStorage; instead, they were retrieved from the default values defined in their corresponding Settings class.
 -  Additionally, whenever Message List–related display settings were being saved, they were not persisted because the corresponding storage editors were not committing the changes.
### 💡 Solution
 - Integrate the message list preferences so they combine correctly with existing general and display settings.
 -  Commit changes to the preference store when the corresponding settings are saved.

### CODE REVIEW

File: legacy/core/src/main/java/com/fsck/k9/preferences/DefaultGeneralSettingsManager.kt [hunk 1]
```diff
@@ -93,6 +96,16 @@ internal class DefaultGeneralSettingsManager(
                 display = generalSettings.display.copy(visualSettings = visualSettings),
             )
         }
+        .combine(messageListPreferencesManager.getConfigFlow()) { generalSettings, messageListSettings ->
+            logger.debug { "messageListSettings: $messageListSettings" }
```
Comment (dani-zilla) [inline legacy/core/src/main/java/com/fsck/k9/preferences/DefaultGeneralSettingsManager.kt:101]: Worth noting that logger is currently not recommended:
```
"Use a net.thunderbird.core.logging.Logger instance via dependency injection instead. " +
        "This class will be removed in a future release.",
```

**Review by dani-zilla — CHANGES_REQUESTED** [review]
I think we could drop the logging, but I did want to ask if you were able to reproduce this in a newer version of the app. I could not reproduce it on v14 from Google Play or v17 from a fresh debug build, not with the existing views or compose either. Do you have any additional info on how this fix could be tested between the latest beta and this version? 

Thanks!

File: legacy/core/src/main/java/com/fsck/k9/preferences/DefaultGeneralSettingsManager.kt (hunk 1 above)
Comment (shamim-emon) [reply legacy/core/src/main/java/com/fsck/k9/preferences/DefaultGeneralSettingsManager.kt:101]: Updated, now injecting  net.thunderbird.core.logging.Logger instance instead as per suggestion.

**Comment by shamim-emon** [comment]
> I think we could drop the logging, but I did want to ask if you were able to reproduce this in a newer version of the app. I could not reproduce it on v14 from Google Play or v17 from a fresh debug build, not with the existing views or compose either. Do you have any additional info on how this fix could be tested between the latest beta and this version?
> 
> Thanks!

@dani-zilla  I am able to reproduce this on latest debug build.  In-case you don't see the issue, toggle  Colorize contact pictures value and then restart the app, you will see this value along with any value from MessageList settings is not persisted.

**Review by dani-zilla — APPROVED** [review]
Was able to reproduce it with the force quit method. Thanks for that! Bug seems to be fixed in build and looks good to me. Thanks!
