### PR TITLE
OpenPGP provider and status fixes

### LINKED ISSUE #1150: Can't send message without crypto provider
### Expected behaviour

Message should be sent unsigned.
### Actual behaviour

Without an installed crypto provider sending a message fails with the message "No key configured for signing! Please check your settings."
### Steps to reproduce
1. Open compose activity
2. Fill in recipient, subject and message text
3. Tap 'send'
### Environment

K-9 Mail version: master / 833e1cc4186b6703cef28a9dc825d7d68d24c1b8

Android version: 5.1

### PR DESCRIPTION
**Pull request by Valodim**
The two commits in this PR fix #1150 and #1151, respectively

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Does it also fix #1153 and #1160 ?

**Comment by Valodim** [comment]
It doesn't.

**Comment by philipwhiuk** [comment]
Ok no worries.

**Comment by cketti** [comment]
Still doesn't work for me without a crypto provider configured.

**Comment by philipwhiuk** [comment]
With my PR as well it works for me.

**Comment by cketti** [comment]
As far as I can tell `ComposeCryptoStatus.shouldUsePgpMessageBuilder()` returns `true` because the default 'crypto mode' of 'opportunistic' is used. Whether or not a crypto provider is configured doesn't factor into the decision.

**Comment by Valodim** [comment]
Haha, I fixed it in my first commit, then broke it in the second. Derp.

Working on this right now.

**Comment by Valodim** [comment]
Alrighty, that should be fixed. I also moved all openpgpservicconnection handling into the presenter, and added better handling for a lost service connection. I tested a couple of scenarios while installing and deinstalling openkeychain all around, and it seems more robust to me now.

I wonder what trivial usage scenario I missed this time ;)

File: k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java [hunk 1]
```diff
@@ -3022,7 +2995,8 @@ public void onMessageBuildCancel() {
     @Override
     public void onMessageBuildException(MessagingException me) {
         Log.e(K9.LOG_TAG, "Error sending message", me);
-        Toast.makeText(MessageCompose.this, getString(R.string.send_aborted), Toast.LENGTH_LONG).show();
+        Toast.makeText(MessageCompose.this,
+                getString(R.string.send_failed_reason, me.getLocalizedMessage()), Toast.LENGTH_LONG).show();
         currentMessageBuilder = null;
```
Comment (philipwhiuk) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: I'm not convinced by this - it's not like the actual "send" (i.e. the I/O) actually happens.

**Comment by philipwhiuk** [comment]
> Haha, I fixed it in my first commit, then broke it in the second. Derp.

It's annoying this is all front-end code. It would be nice get some UTs on it.

File: k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java (hunk 1 above)
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: Please don't display exception messages to the user. We need better error reporting, but that's not what I had in mind :smile: 

Maybe "Send aborted due to an error"?

Comment (Valodim) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: I did this because otherwise messages like "Signing key not found" would not get through to the user, giving them no clue whatsoever what was wrong other than "Send aborted"...

Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: I figured. But what we really want is an error code -> error message mapping inside K-9 Mail. That way we can provide appropriate error messages that can be localized by our translators.

Comment (Valodim) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: Right. We already have a class for openpgp api errors, which also does error codes. We don't really use that in OpenKeychain yet but I have some ideas how to do that from our internal error logs. I also wanted to pass a pending intent result which shows the log we keep internally, which may be helpful for debugging.

Anyways, I reckon I'll wait with that until there is better error handling in k9 first.
