### PR TITLE
migration: fix NPE if textContent is null (fixes #1208)

### LINKED ISSUE #1208: NPE in migration if textContent is null for a text/plain mail
```
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
 	at com.fsck.k9.mailstore.migrations.MigrationTo51.insertTextualPartIntoDatabase(MigrationTo51.java:593)
 	at com.fsck.k9.mailstore.migrations.MigrationTo51.migrateSimpleMailContent(MigrationTo51.java:400)
 	at com.fsck.k9.mailstore.migrations.MigrationTo51.db51MigrateMessageFormat(MigrationTo51.java:111)
```

### PR DESCRIPTION
**Pull request by Valodim**
if textContent/htmlContent is empty but should be put in the database, the part is marked as DATA_LOCATION__MISSING

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/mailstore/migrations/MigrationTo51.java [hunk 1]
```diff
@@ -587,20 +590,32 @@ private static MimeStructureState insertTextualPartIntoDatabase(SQLiteDatabase d
...
-        byte[] contentBytes = contentOutputStream.toByteArray();
+        byte[] contentBytes;
+        int decodedBodySize;
+        int dataLocation;
+        if (content != null) {
+            ByteArrayOutputStream contentOutputStream = new ByteArrayOutputStream();
+            QuotedPrintableOutputStream quotedPrintableOutputStream =
+                    new QuotedPrintableOutputStream(contentOutputStream, false);
+            quotedPrintableOutputStream.write(content.getBytes());
+            quotedPrintableOutputStream.flush();
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/mailstore/migrations/MigrationTo51.java]: General note: Closing a stream will also flush the output. It has the additional benefit of being the right thing to do and not being flagged by static analyzers or runtime checks.

File: k9mail/src/main/java/com/fsck/k9/mailstore/migrations/MigrationTo51.java [hunk 2]
```diff
@@ -556,9 +556,12 @@ private static MimeStructureState insertBodyAsMultipartAlternative(SQLiteDatabas
         mimeHeader.setHeader(MimeHeader.HEADER_CONTENT_TYPE,
                 String.format("multipart/alternative; boundary=\"%s\";", boundary));
 
+        int dataLocation = textContent != null || htmlContent != null
+                ? DATA_LOCATION__IN_DATABASE : DATA_LOCATION__MISSING;
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/mailstore/migrations/MigrationTo51.java]: Code style: `?` goes to the end of the preceding line
