### PR TITLE
WebDAV: Use the proper sendRequest mechanism to append messages

### LINKED ISSUE #1500: Webdav (Exchange) sending email is broken since v5.109 (alpha)
Android version: 6.01

Using K-9 Mail v5.010 (stable) i could send emails using my old WEBDAV account.
But never delete emails on the server.
Then Updated to K-9 Mail v5.109 (alpha) / and also to K-9 Mail v5.110 (alpha).
Now I can delete emails on the server, but I can not send emails any more.
They end up on the outgoing folder.
Sorry I can't tell you the error message. The message text is too long so it's truncated...

Then Downgraded (titanium Backup / also the database) and sending emails is working again.

### PR DESCRIPTION
**Pull request by philipwhiuk**
This should fix #1500 

I say should because I don't have a WebDAV set-up any more but the code does roughly the same as it did, only using the proper sendRequest code to handle auth errors - so I think it's fairly safe.

### CODE REVIEW

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/webdav/WebDavFolderTest.java [hunk 1]
```diff
@@ -75,21 +77,27 @@
...
+    @Captor
+    private ArgumentCaptor<String> urlCaptor;
+    @Captor
+    private ArgumentCaptor<StringEntity> entityCaptor;
 
     private WebDavFolder folder;
 
     private WebDavFolder destinationFolder;
+    private String storeUrl = "https://localhost/webDavStoreUrl";
+    private String storeName = "testFolder";
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/webdav/WebDavFolderTest.java]: This should probably be `folderName` rather than `storeName`.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/webdav/WebDavFolderTest.java [hunk 2]
```diff
@@ -529,4 +534,20 @@ public void appendWebDavMessages_replaces_messages_with_WebDAV_versions() throws
...
+        Message existingMessage = mock(Message.class);
+        existingMessages.add(existingMessage);
+        String messageUid = "testMessageUid";
+        when(existingMessage.getUid()).thenReturn(messageUid);
+
+        folder.appendWebDavMessages(existingMessages);
+
+        verify(mockStore).sendRequest(urlCaptor.capture(), eq("PUT"), entityCaptor.capture(),
+                Matchers.<Map<String, String>>eq(null), eq(true));
+        assertTrue(urlCaptor.getValue().startsWith(storeUrl+"/"+storeName+"/"+messageUid));
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/webdav/WebDavFolderTest.java]: Code style: missing spaces

**Comment by markusb68** [comment]
Still now working in K-9 Mail v5.204:
screenshot_20170224-133307

The last version I could SEND emails with is 5.010.
All later Versions broke WEBDAV-Exchange Email sending.

Can't you just check what has been changed since 5.010 in that part of code and roll it back ?

Is it possible to use SMTP for sending emails?
The (sending) Server Settings don't open in the DEVDAV account.
