### PR TITLE
User selected Account is lost on screen rotation when setting up "Unread" widget

### LINKED ISSUE #4936: User selected Account is lost on screen rotation
**Describe the bug**
User-selected account is lost on screen rotation when setting up an 'unread widget'.

**To Reproduce**
1. Go to the home screen and create 'unread widget'.
2. Click on 'Account' and select user mail-box.
3. Rotate the device or any kind of config changes.
4. The selected account is lost.

**Expected behavior**
The app should retain the user-selected account.

**Screenshots**
image

**Environment (please complete the following information):**
 - K-9 Mail version:  5.6
 - Android version: 8.1.0
 - Device: Nexus 5X
 - Account type:  IMAP, POP3

### PR DESCRIPTION
**Pull request by AlexKDawson**
Fixes #4936 

Saves the folder and account information in onSaveInstanceState and reloads them in onCreatePreferencesFix, so that the information doesn't go away on rotate.

### CODE REVIEW

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 1]
```diff
@@ -32,6 +32,27 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
     private var selectedAccountUuid: String? = null
     private var selectedFolderId: Long? = null
 
+    override fun onSaveInstanceState(outState: Bundle) {
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:35]: In the K-9 Mail code base typically one of the `onCreate*()` methods is the first one in a Fragment/Activity. Please move this method below `onCreatePreferencesFix()`.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 2]
```diff
@@ -32,6 +32,27 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
...
+                outState.putString(SELECTED_ACCOUNT_UUID_STATE, localSelectedAccountUuid)
+            }
+
+            if (localSelectedFolderId != null) {
+                outState.putLong(SELECTED_FOLDER_ID_STATE, localSelectedFolderId)
+            }
+
+            if (localSelectedFolderSummary != null) {
+                outState.putString(SELECTED_FOLDER_SUMMARY, localSelectedFolderSummary)
+            }
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:52]: The indentation is off here. Please fix.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 3]
```diff
@@ -32,6 +32,27 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
...
+        super.onSaveInstanceState(outState)
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:53]: We usually call through to the super method first. Please move this call to the top of the method.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 4]
```diff
@@ -32,6 +32,27 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
     private var selectedAccountUuid: String? = null
     private var selectedFolderId: Long? = null
 
+    override fun onSaveInstanceState(outState: Bundle) {
+            // Use local variable to avoid mutable property issues.
+            // putString supports null storage, but we will type check for consistency
+            var localSelectedAccountUuid = selectedAccountUuid
+            var localSelectedFolderId = selectedFolderId
+            var localSelectedFolderSummary = unreadFolder.summary.toString()
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:40]: I value consistency in general. But this feels like overdoing it. To deal with the mutability and nullability of `selectedFolderId` you can use a construct like this:

```kotlin
selectedFolderId?.let { selectedFolderId ->
    outState.putLong(SELECTED_FOLDER_ID_STATE, selectedFolderId)
}
```

You can also put this logic into an extension function to make it nicer to read at the call site:

```kotlin
override fun onSaveInstanceState(outState: Bundle) {
    // …
    outState.putLongIfPresent(SELECTED_FOLDER_ID_STATE, selectedFolderId)
    // …
}

// …

private fun Bundle.putLongIfPresent(key: String, value: Long?) {
    if (value != null) {
        putLong(key, value)
    }
}
```

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 5]
```diff
@@ -62,6 +83,24 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
...
+                if (savedInstanceState.containsKey(SELECTED_FOLDER_ID_STATE) &&
+                        savedInstanceState.containsKey(SELECTED_FOLDER_SUMMARY)) {
+                    var folderId = savedInstanceState.getLong(SELECTED_FOLDER_ID_STATE)
+                    var folderSummary = savedInstanceState.getString(SELECTED_FOLDER_SUMMARY)
+                    if (folderSummary != null) {
+                        handleChooseFolder(folderId, folderSummary)
+                    }
+                }
+            }
+        }
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:103]: Please extract this code to a new method.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 6]
```diff
@@ -62,6 +83,24 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
             startActivityForResult(intent, REQUEST_CHOOSE_FOLDER)
             false
         }
+
+        if (savedInstanceState != null) {
+            if (savedInstanceState.containsKey(SELECTED_ACCOUNT_UUID_STATE)) {
+                var accountUuid = savedInstanceState.getString(SELECTED_ACCOUNT_UUID_STATE)
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:89]: Please use `val` instead of `var`. See https://kotlinlang.org/docs/tutorials/kotlin-for-py/declaring-variables.html

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt (hunk 4 above)
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:40]: Rather than saving the summary value of the `Preference` please write the folder display name to a property in `handleChooseFolder()` and use that property when saving state.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 7]
```diff
@@ -174,6 +213,10 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
         private const val REQUEST_CHOOSE_ACCOUNT = 1
         private const val REQUEST_CHOOSE_FOLDER = 2
 
+        private const val SELECTED_ACCOUNT_UUID_STATE = "com.fsck.k9.widget.unread.selectedAccountUuid"
+        private const val SELECTED_FOLDER_ID_STATE = "com.fsck.k9.widget.unread.selectedFolderId"
+        private const val SELECTED_FOLDER_SUMMARY = "com.fsck.k9.widget.unread.unreadFolder.summary"
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:218]: We typically prefix the constant names with `STATE_`. Please change.

**Review by cketti — CHANGES_REQUESTED** [review]
Functionally this is good :+1: To make the code feel closer to the rest of the K-9 Mail code base some changes are necessary.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 8]
```diff
@@ -158,9 +129,36 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
...
+                    val folderSummary = savedInstanceState.getString(STATE_SELECTED_FOLDER_SUMMARY)
+                    if (folderSummary != null) {
+                        handleChooseFolder(folderId, folderSummary)
+                    }
+                }
+            }
+        }
+    }
+
+    private fun Bundle.putLongIfPresent(key: String, value: Long?) {
```
Comment (AlexKDawson) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:156]: Would this be the correct place to put the putLongIfPresent function? This method to extending a class is pretty new to me and I'm unsure of best practices.

Comment (AlexKDawson) [reply app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:156]: ^ @cketti
Also, This is ready for re-review

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 9]
```diff
@@ -62,6 +63,15 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
             startActivityForResult(intent, REQUEST_CHOOSE_FOLDER)
             false
         }
+
+        loadSavedState(savedInstanceState)
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:67]:
```suggestion
        if (savedInstanceState != null) {
            restoreInstanceState(savedInstanceState)
        }
```

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 10]
```diff
@@ -62,6 +63,15 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
...
+    }
+
+    override fun onSaveInstanceState(outState: Bundle) {
+        super.onSaveInstanceState(outState)
+        outState.putString(STATE_SELECTED_ACCOUNT_UUID, selectedAccountUuid)
+        outState.putLongIfPresent(STATE_SELECTED_FOLDER_ID, selectedFolderId)
+        outState.putString(STATE_SELECTED_FOLDER_SUMMARY, selectedFolderDisplayName.toString())
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:74]:
```suggestion
        outState.putString(STATE_SELECTED_FOLDER_DISPLAY_NAME, selectedFolderDisplayName)
```

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 11]
```diff
@@ -119,9 +129,36 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
 
     private fun handleChooseFolder(folderId: Long, folderDisplayName: String) {
         selectedFolderId = folderId
+        selectedFolderDisplayName = folderDisplayName
         unreadFolder.summary = folderDisplayName
     }
 
+    private fun loadSavedState(savedInstanceState: Bundle?) {
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:136]: I'd rename this method to `restoreInstanceState()`. This is more consistent with the Android terminology.

Also, please move this method to either right before or right after `onSaveInstanceState()`. Code to save and restore state should be close to each other.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 12]
```diff
@@ -119,9 +129,36 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
...
+                if (savedInstanceState.containsKey(STATE_SELECTED_FOLDER_ID) &&
+                    savedInstanceState.containsKey(STATE_SELECTED_FOLDER_SUMMARY)) {
+                    val folderId = savedInstanceState.getLong(STATE_SELECTED_FOLDER_ID)
+                    val folderSummary = savedInstanceState.getString(STATE_SELECTED_FOLDER_SUMMARY)
+                    if (folderSummary != null) {
+                        handleChooseFolder(folderId, folderSummary)
+                    }
+                }
+            }
+        }
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:153]: Checking if the key exists and have an additional null check feels like a bit much. You can write it like this:

```suggestion
        val accountUuid = savedInstanceState.getString(STATE_SELECTED_ACCOUNT_UUID)
        if (accountUuid != null) {
            handleChooseAccount(accountUuid)

            val folderId = savedInstanceState.getLongOrNull(STATE_SELECTED_FOLDER_ID)
            val folderSummary = savedInstanceState.getString(STATE_SELECTED_FOLDER_SUMMARY)
            if (folderId != null && folderSummary != null) {
                handleChooseFolder(folderId, folderSummary)
            }
        }
```

with 

```kotlin
private fun Bundle.getLongOrNull(key: String): Long? {
    return if (containsKey(key)) getLong(key) else null
}
```

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt (hunk 8 above)
Comment (cketti) [reply app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:156]: If in doubt check other files. I usually put those helper extension functions below regular instance methods. In this case right above the companion object.

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 13]
```diff
@@ -174,6 +211,10 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
         private const val REQUEST_CHOOSE_ACCOUNT = 1
         private const val REQUEST_CHOOSE_FOLDER = 2
 
+        private const val STATE_SELECTED_ACCOUNT_UUID = "com.fsck.k9.widget.unread.selectedAccountUuid"
+        private const val STATE_SELECTED_FOLDER_ID = "com.fsck.k9.widget.unread.selectedFolderId"
+        private const val STATE_SELECTED_FOLDER_SUMMARY = "com.fsck.k9.widget.unread.unreadFolder.summary"
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:216]:
```suggestion
        private const val STATE_SELECTED_FOLDER_DISPLAY_NAME = "com.fsck.k9.widget.unread.selectedFolderDisplayName"
```

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt [hunk 14]
```diff
@@ -31,6 +31,7 @@ class UnreadWidgetConfigurationFragment : PreferenceFragmentCompat() {
 
     private var selectedAccountUuid: String? = null
     private var selectedFolderId: Long? = null
+    private var selectedFolderDisplayName: String? = null
```
Comment (cketti) [inline app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:34]: This property has the same "lifetime" as `selectedFolderId`, i.e. it should be set to `null` whenever `selectedFolderId` is set to `null`.

**Review by cketti — CHANGES_REQUESTED** [review]

File: app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt (hunk 8 above)
Comment (AlexKDawson) [reply app/k9mail/src/main/java/com/fsck/k9/widget/unread/UnreadWidgetConfigurationFragment.kt:156]: Sounds good. Thanks for you patience

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Thanks :+1:
