### PR TITLE
Fix notification actions

### LINKED ISSUE #1822: "Mark as read" not working from notification
### Expected behavior
Selecting "mark as read" should mark the email as read and dismiss the notification

### Actual behavior
Absolutely nothing!

### Steps to reproduce
1. Send email to self
2. Expand the notification
3. Select "Mark as read"

### Environment
K-9 Mail version: 5.115

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by cketti**
Don't use `Parcelable` extras in Intents that are launched from notifications.

Fixes #1822

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java [hunk 1]
```diff
@@ -1302,18 +1303,16 @@ private void processDraftMessage(MessageViewInfo messageViewInfo) {
 
         if (k9identity.containsKey(IdentityField.ORIGINAL_MESSAGE)) {
             relatedMessageReference = null;
-            try {
-                String originalMessage = k9identity.get(IdentityField.ORIGINAL_MESSAGE);
-                MessageReference messageReference = new MessageReference(originalMessage);
+            String originalMessage = k9identity.get(IdentityField.ORIGINAL_MESSAGE);
+            MessageReference messageReference = MessageReference.parse(originalMessage);
 
+            if (messageReference != null) {
```
Comment (philipwhiuk) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: Consider an `else {` case with some logging?

File: k9mail/src/main/java/com/fsck/k9/activity/MessageReference.java [hunk 2]
```diff
@@ -1,94 +1,63 @@
...
-import com.fsck.k9.mailstore.LocalFolder;
-import com.fsck.k9.mailstore.LocalMessage;
 import com.fsck.k9.mail.filter.Base64;
 
-import java.util.StringTokenizer;
+import static com.fsck.k9.helper.Preconditions.checkNotNull;
+
+
+public class MessageReference {
+    private static final char IDENTITY_VERSION_1 = '!';
```
Comment (philipwhiuk) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageReference.java]: Well this is a hideous way of versioning (I know you didn't introduce this code so I'm not asking for it to be fixed).

File: k9mail/src/test/java/com/fsck/k9/activity/MessageReferenceTest.java [hunk 3]
```diff
@@ -80,25 +82,30 @@ public void checkMessageReferenceWithChangedFlag() {
...
+        MessageReference messageReference =
+                MessageReference.parse("!:%^&%^*$&$by&(BYWkh:Zm9%^@sZGVy:MT-35#$AxMDEwMTA=:ANSWE!RED");
+
+        assertNull(messageReference);
     }
 
     @Test
     public void equalsWithAnObjectShouldReturnFalse() {
-        MessageReference messageReference = new MessageReference(null, null, null, null);
+        MessageReference messageReference = new MessageReference("a", "b", "c", null);
```
Comment (philipwhiuk) [inline k9mail/src/test/java/com/fsck/k9/activity/MessageReferenceTest.java]: Should we still be testing the null case?

Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/activity/MessageReferenceTest.java]: What do you mean by null case?

Comment (philipwhiuk) [inline k9mail/src/test/java/com/fsck/k9/activity/MessageReferenceTest.java]: You're passing in values instead of null because you added pre-conditions - is it worth testing the existence of the pre-conditions? I couldn't see any.

Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/activity/MessageReferenceTest.java]: It can't hurt. But there's not too much value in those kind of tests.

**Comment by cketti** [comment]
Added some tests for `MessageReference`.
