### PR TITLE
Backport updating message reference flags from earlier commit - fixes #1250

### LINKED ISSUE #1250: Reply flag is not set anymore when replying to a mail
### Expected behaviour

Reply flag is set when replying to a mail.
### Actual behaviour

When replying to a mail I do not see a reply flag for the original mail I replied to. When checking the account with a different client (web/Thunderbird) I do not see a flag, too. So it is no frontend bug, the flag is not set anymore, beginning with 5.108.
### Steps to reproduce

See above.
### Environment

K-9 Mail version: 5.108

Android version: CM 12.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

### PR DESCRIPTION
**Pull request by philipwhiuk**

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java [hunk 1]
```diff
@@ -2982,10 +2982,30 @@ public void onMessageBuildSuccess(MimeMessage message, boolean isDraft) {
             currentMessageBuilder = null;
             new SendMessageTask(getApplicationContext(), mAccount, mContacts, message,
                     mDraftId != INVALID_DRAFT_ID ? mDraftId : null).execute();
+            updateReferencedMessage();
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java]: This triggers database operations in the calling thread. We should probably call it from `SendMessageTask`.
