### PR TITLE
Remove ImapFolder caching

### LINKED ISSUE #4412: When opening message during remote search K-9 doens't load the body
### Steps to reproduce
1. start a remote search that will return results that are not yet in your local db
2. while search results are still being returned open a message that is not yet in your local db
3. get a toast with "Remote search failed" and one with "Connection Error" and the body of the message you wanted to open isn't being loaded

### Environment
K-9 Mail version: 5.703

Android version: Android 8/LineageOS 15

Account type (IMAP, POP3, WebDAV/Exchange): Imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

```
12-27 19:49:29.304 26061  3391 V ImapResponseParser: conn33723811<<<#null# [OK, [CLOSED], Previous mailbox closed.]
12-27 19:49:29.305 26061  3391 V ImapResponseParser: conn33723811<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, NonJunk, $label1, Junk, $label2, $label4, $label3, $Forwarded, $label5]]
12-27 19:49:29.305 26061  3391 V ImapResponseParser: conn33723811<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
12-27 19:49:29.305 26061  3391 V ImapResponseParser: conn33723811<<<#null# [41147, EXISTS]
12-27 19:49:29.305 26061  3391 V ImapResponseParser: conn33723811<<<#null# [0, RECENT]
12-27 19:49:29.305 26061  3391 V ImapResponseParser: conn33723811<<<#null# [OK, [UNSEEN, 29251], First unseen.]
12-27 19:49:29.306 26061  3391 V ImapResponseParser: conn33723811<<<#null# [OK, [UIDVALIDITY, 1508270677], UIDs valid]
12-27 19:49:29.306 26061  3391 V ImapResponseParser: conn33723811<<<#null# [OK, [UIDNEXT, 49140], Predicted next UID]
12-27 19:49:29.306 26061  3391 V ImapResponseParser: conn33723811<<<#null# [OK, [HIGHESTMODSEQ, 110437], Highest]
12-27 19:49:29.307 26061  3391 V ImapResponseParser: conn33723811<<<#109# [OK, [READ-ONLY], Examine completed (0.058 + 0.000 + 0.057 secs).]
12-27 19:49:29.307 26061  3391 D ImapFolder: Got untagged EXISTS with value 41147 for BubuMail:INBOX/pool-3-thread-3/conn33723811
12-27 19:49:29.307 26061  3391 D ImapFolder: Got UidNext = 49140 for BubuMail:INBOX/pool-3-thread-3/conn33723811
12-27 19:49:29.308 26061  3391 V ImapConnection: conn33723811>>> 110 UID FETCH 48595 (UID FLAGS INTERNALDATE RFC822.SIZE BODY.PEEK[HEADER.FIELDS (date subject from content-type to cc reply-to message-id references in-reply-to X-K9mail-Identity)])
12-27 19:49:29.408 26061  3391 V ImapConnection: conn33723811<<<#null# [40744, FETCH, [UID, 48595, FLAGS, [\Seen, NonJunk], INTERNALDATE, 17-Dec-2019 17:48:23 +0100, RFC822.SIZE, 1380, BODY, [HEADER.FIELDS, [DATE, SUBJECT, FROM, CONTENT-TYPE, TO, CC, REPLY-TO, MESSAGE-ID, REFERENCES, IN-REPLY-TO, X-K9MAIL-IDENTITY]], To: bubu@bubu1.eu
12-27 19:49:29.408 26061  3391 V ImapConnection: From: Marcus Hoffmann <marcus@tahoffmann.de>
12-27 19:49:29.408 26061  3391 V ImapConnection: Subject: test
12-27 19:49:29.408 26061  3391 V ImapConnection: Message-ID: <5e34a344-58e4-29eb-c26d-f9bf01b87d31@tahoffmann.de>
12-27 19:49:29.408 26061  3391 V ImapConnection: Date: Tue, 17 Dec 2019 17:48:22 +0100
12-27 19:49:29.408 26061  3391 V ImapConnection: Content-Type: text/plain; charset=utf-8
12-27 19:49:29.408 26061  3391 V ImapConnection: 
12-27 19:49:29.408 26061  3391 V ImapConnection: ]]
12-27 19:49:29.409 26061  3391 V ImapFolder: Stored uid '48595' for msgSeq 40744 into map
12-27 19:49:29.413 26061  3391 V ImapConnection: conn33723811<<<#110# [OK, Fetch completed (0.001 + 0.000 secs).]
12-27 19:49:29.414 26061  3391 V ImapConnection: conn33723811>>> 111 UID FETCH 48595 (UID BODYSTRUCTURE)
12-27 19:49:29.439  3913  5841 D AudioService: Stream muted, skip playback
12-27 19:49:29.602 26061 26061 D MessageViewFragment: MessageView displaying message MessageReference{accountUuid='4e29bcd8-081e-45f2-80cd-e02784e2a434', folderServerId='INBOX', uid='48597', flag=null}
12-27 19:49:29.602 26061 26061 D MessageLoaderHelper: Creating new local message loader
12-27 19:49:29.606  3663  3663 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
12-27 19:49:29.610 26061  3391 V ImapConnection: conn33723811<<<#null# [40744, FETCH, [UID, 48595, BODYSTRUCTURE, [text, plain, [charset, utf-8], NIL, NIL, 7bit, 11, 2, NIL, NIL, [en-US], NIL]]]
12-27 19:49:29.610 26061  3391 V ImapFolder: Stored uid '48595' for msgSeq 40744 into map
12-27 19:49:29.611 26061  3391 V ImapConnection: conn33723811<<<#111# [OK, Fetch completed (0.139 + 0.000 + 0.138 secs).]
12-27 19:49:29.649 26061 26077 I MessagingController: Running command 'loadMessageRemotePartial', seq = 38 (foreground priority)
12-27 19:49:29.659 26061  3391 D BinaryTempFileBody$Bina: Deleting temporary binary file: body5315428824617549830.tmp
12-27 19:49:29.689 26061  3391 V LockableDatabase: LockableDatabase: Transaction ended, took 22 ms / com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1295)
12-27 19:49:29.692 26061  3391 V ImapConnection: conn33723811>>> 112 NOOP
12-27 19:49:29.731  3663  3663 I app_process: The ClassLoaderContext is a special shared library.
12-27 19:49:29.764  3663  3663 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
12-27 19:49:29.780  3663  3670 W MessageQueue: Handler (android.os.Handler) {e318478} sending message to a Handler on a dead thread
12-27 19:49:29.780  3663  3670 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {e318478} sending message to a Handler on a dead thread
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:662)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:631)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:601)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.Handler.post(Handler.java:357)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
12-27 19:49:29.780  3663  3670 W MessageQueue: 	at android.os.Binder.execTransact(Binder.java:697)
12-27 19:49:29.780  3663  3663 I app_process: System.exit called, status: 0
12-27 19:49:29.780  3663  3663 I AndroidRuntime: VM exiting with result code 0.
12-27 19:49:29.816 26061  3391 V ImapResponseParser: conn33723811<<<#112# [OK, NOOP completed (0.028 + 0.000 + 0.027 secs).]
12-27 19:49:29.818 26061 26077 E MessagingController: Error while loading remote message
12-27 19:49:29.818 26061 26077 E MessagingController: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[])' on a null object reference
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:811)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:750)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:739)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:111)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:147)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.open(ImapFolder.java:116)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.backend.imap.ImapSync.downloadMessage(ImapSync.java:254)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.downloadMessage(ImapBackend.java:122)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.controller.MessagingController.loadMessageRemoteSynchronous(MessagingController.java:1319)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.controller.MessagingController.access$1000(MessagingController.java:113)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.controller.MessagingController$17.run(MessagingController.java:1278)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:220)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:113)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
12-27 19:49:29.818 26061 26077 E MessagingController: 	at java.lang.Thread.run(Thread.java:764)
12-27 19:49:29.818 26061 26077 I MessagingController:  Command 'loadMessageRemotePartial' completed
12-27 19:49:29.819 26061  3391 D ImapConnection: Connecting to imap.bubu1.eu as imap.bubu1.eu/176.9.145.28
12-27 19:49:30.067 26061  3391 V ImapConnection: conn111138035 <<< #null# [OK, [CAPABILITY, IMAP4rev1, SASL-IR, LOGIN-REFERRALS, ID, ENABLE, IDLE, LITERAL+, AUTH=PLAIN], Dovecot ready.]
12-27 19:49:30.067 26061  3391 D ImapConnection: Saving [AUTH=PLAIN, LITERAL+, IMAP4REV1, LOGIN-REFERRALS, IDLE, SASL-IR, ID, ENABLE] capabilities for conn111138035
12-27 19:49:30.068 26061  3391 V ImapConnection: conn111138035>>> 2 AUTHENTICATE PLAIN
12-27 19:49:30.078  3674  3674 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
12-27 19:49:30.090 26061  3391 V ImapConnection: conn111138035<<<#+# []
12-27 19:49:30.188  3674  3674 I app_process: The ClassLoaderContext is a special shared library.
12-27 19:49:30.221  3674  3674 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
12-27 19:49:30.226 26061  3391 V ImapResponseParser: conn111138035<<<#2# [OK, [CAPABILITY, IMAP4rev1, SASL-IR, LOGIN-REFERRALS, ID, ENABLE, IDLE, SORT, SORT=DISPLAY, THREAD=REFERENCES, THREAD=REFS, THREAD=ORDEREDSUBJECT, MULTIAPPEND, URL-PARTIAL, CATENATE, UNSELECT, CHILDREN, NAMESPACE, UIDPLUS, LIST-EXTENDED, I18NLEVEL=1, CONDSTORE, QRESYNC, ESEARCH, ESORT, SEARCHRES, WITHIN, CONTEXT=SEARCH, LIST-STATUS, BINARY, MOVE, SNIPPET=FUZZY, PREVIEW=FUZZY, LITERAL+, NOTIFY], Logged in]
12-27 19:49:30.227 26061  3391 D ImapConnection: Saving [URL-PARTIAL, NAMESPACE, LIST-STATUS, PREVIEW=FUZZY, THREAD=REFERENCES, BINARY, SASL-IR, WITHIN, MULTIAPPEND, SEARCHRES, ESORT, CONDSTORE, NOTIFY, I18NLEVEL=1, CATENATE, ID, SORT=DISPLAY, QRESYNC, UNSELECT, ENABLE, THREAD=ORDEREDSUBJECT, UIDPLUS, CHILDREN, CONTEXT=SEARCH, MOVE, SNIPPET=FUZZY, LITERAL+, IMAP4REV1, LOGIN-REFERRALS, IDLE, ESEARCH, SORT, LIST-EXTENDED, THREAD=REFS] capabilities for conn111138035
12-27 19:49:30.229  3674  3687 W MessageQueue: Handler (android.os.Handler) {d41ee1} sending message to a Handler on a dead thread
12-27 19:49:30.229  3674  3687 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {d41ee1} sending message to a Handler on a dead thread
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:662)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:631)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:601)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.Handler.post(Handler.java:357)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
12-27 19:49:30.229  3674  3687 W MessageQueue: 	at android.os.Binder.execTransact(Binder.java:697)
12-27 19:49:30.229 26061  3391 V ImapConnection: conn111138035>>> 3 EXAMINE "INBOX"
12-27 19:49:30.229  3674  3674 I app_process: System.exit called, status: 0
12-27 19:49:30.229  3674  3674 I AndroidRuntime: VM exiting with result code 0.
12-27 19:49:30.327 26061  3391 V ImapResponseParser: conn111138035<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, NonJunk, $label1, Junk, $label2, $label4, $label3, $Forwarded, $label5]]
12-27 19:49:30.328 26061  3391 V ImapResponseParser: conn111138035<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
12-27 19:49:30.328 26061  3391 V ImapResponseParser: conn111138035<<<#null# [41147, EXISTS]
12-27 19:49:30.328 26061  3391 V ImapResponseParser: conn111138035<<<#null# [0, RECENT]
12-27 19:49:30.328 26061  3391 V ImapResponseParser: conn111138035<<<#null# [OK, [UNSEEN, 29251], First unseen.]
12-27 19:49:30.329 26061  3391 V ImapResponseParser: conn111138035<<<#null# [OK, [UIDVALIDITY, 1508270677], UIDs valid]
12-27 19:49:30.329 26061  3391 V ImapResponseParser: conn111138035<<<#null# [OK, [UIDNEXT, 49140], Predicted next UID]
12-27 19:49:30.330 26061  3391 V ImapResponseParser: conn111138035<<<#null# [OK, [HIGHESTMODSEQ, 110437], Highest]
12-27 19:49:30.331 26061  3391 V ImapResponseParser: conn111138035<<<#3# [OK, [READ-ONLY], Examine completed (0.072 + 0.000 + 0.071 secs).]
12-27 19:49:30.332 26061  3391 D ImapFolder: Got untagged EXISTS with value 41147 for BubuMail:INBOX/pool-3-thread-3
12-27 19:49:30.334 26061  3391 D ImapFolder: Got UidNext = 49140 for BubuMail:INBOX/pool-3-thread-3
12-27 19:49:30.336 26061  3391 E MessagingController: Could not complete remote search
12-27 19:49:30.336 26061  3391 E MessagingController: com.fsck.k9.mail.MessagingException: Folder INBOX is not open.
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.checkOpen(ImapFolder.java:1311)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.fetch(ImapFolder.java:608)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.backend.imap.CommandFetchMessage.fetchMessage(CommandFetchMessage.kt:52)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.backend.imap.CommandFetchMessage.fetchMessage(CommandFetchMessage.kt:27)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.fetchMessage(ImapBackend.java:184)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.controller.MessagingController.loadSearchResultsSynchronous(MessagingController.java:656)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:590)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:546)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-27 19:49:30.336 26061  3391 E MessagingController: 	at java.lang.Thread.run(Thread.java:764)
12-27 19:49:30.337 26061  3391 E MessagingController: com.fsck.k9.mail.MessagingException: Folder INBOX is not open.
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.checkOpen(ImapFolder.java:1311)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapFolder.fetch(ImapFolder.java:608)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.backend.imap.CommandFetchMessage.fetchMessage(CommandFetchMessage.kt:52)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.backend.imap.CommandFetchMessage.fetchMessage(CommandFetchMessage.kt:27)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.fetchMessage(ImapBackend.java:184)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.controller.MessagingController.loadSearchResultsSynchronous(MessagingController.java:656)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:590)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:546)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-27 19:49:30.337 26061  3391 E MessagingController: 	at java.lang.Thread.run(Thread.java:764)

```

### PR DESCRIPTION
**Pull request by cketti**
The cache was causing problems when a folder was accessed from two threads at the same time. Also, there was no invalidation mechanism that removed folders that had been removed from the server.

The easy fix is to get rid of this cache. There's no state in `ImapFolder` that survives closing the folder anyway.

Fixes #4412

### CODE REVIEW

File: mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/ImapStoreTest.java [hunk 1]
```diff
@@ -60,16 +60,6 @@ public void getFolder_shouldReturnImapFolderInstance() throws Exception {
...
     }
 
-    @Test
-    public void getFolder_calledTwice_shouldReturnFirstInstance() throws Exception {
-        String folderName = "Trash";
-        ImapFolder imapFolder = imapStore.getFolder(folderName);
-
-        ImapFolder result = imapStore.getFolder(folderName);
-
-        assertEquals(imapFolder, result);
```
Comment (cketti) [inline mail/protocols/imap/src/test/java/com/fsck/k9/mail/store/imap/ImapStoreTest.java:70]: Fun fact: This didn't work as intended because `assertEquals()` was used instead of `assertSame()`.
