### PR TITLE
Fix of "Configure manually" distracts users to hit the "Next" button

### LINKED ISSUE #8512: "Configure manually" distracts users to hit the "Next" button
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

10

### Device model

LG G7 ThinQ

### Steps to reproduce

Open Thunderbird
* Prompt 1:  Click on "Add an email account now"
* Prompt 2: Enter an email address to a custom server (not gmail, hotmail, etc)
* Prompt 3: Click on "Configure manually"
image

* Click "Next"
* Prompt 4:
image

### Expected behavior

1: The background color should remain unchanged when clicking on "Configure manually" since it is not a button.
2: The text "Configure manually" should be black, as it's just text

These issues have led some users to believe that manual configuration of Thunderbird is not possible, as they may overlook the "Next" button. For example, see the comment at https://blog.thunderbird.net/2024/10/thunderbird-for-android-8-0-takes-flight/#comment-5773.

### Actual behavior

1: The background color is changed to gray when you click on "Configure manually" which indicates that it's a button
2: The text "Configure manually" is blue, this color suggests it is a link intended to open the manual configuration prompt.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by shamim-emon**
In manual mail configuration screen made the following update:
1: Toggle click ripple effect  on "Configure manually" based on configuration availability.
2: Custom color removal of the text "Configure manually" so it doesn't feel like link anymore.
- Fixes #8512

### CODE REVIEW

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultHeaderView.kt [hunk 1]
```diff
@@ -25,6 +28,12 @@ internal fun AutoDiscoveryResultHeaderView(
 ) {
     Row(
         modifier = Modifier
+            .clickable(
+                indication = null,
+                interactionSource = remember { MutableInteractionSource() }
+            ){
+
+            }
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultHeaderView.kt:36]: Whenever you find yourself doing something non-intuitive like "adding a click listener to disable clicks on an view that is normally not clickable", you're likely missing something. In this case it's https://github.com/thunderbird/thunderbird-android/blob/ac19c2765c9ba3d8ac85b4b0170b5cc1361de758/feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultView.kt#L39

The `Surface` composable that contains `AutoDiscoveryResultHeaderView` is clickable on purpose. Expanding the box will display the server settings if a configuration was found. This functionality needs to be retained.

Instead of overriding the `clickable` modifier on `Surface` via another `clickable` modifier on `AutoDiscoveryResultHeaderView`, the original `clickable` modifier should only be set if a configuration was found.

**Review by cketti — CHANGES_REQUESTED** [review]

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultHeaderView.kt (hunk 1 above)
Comment (shamim-emon) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultHeaderView.kt]: @cketti Done!

File: feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultView.kt [hunk 2]
```diff
@@ -36,7 +36,7 @@ internal fun AutoDiscoveryResultView(
                     color = Color.Gray.copy(alpha = 0.5f),
                     shape = MainTheme.shapes.small,
                 )
-                .clickable { expanded.value = !expanded.value },
+                .clickable(enabled = settings != null) { expanded.value = !expanded.value },
```
Comment (cketti) [inline feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultView.kt:39]: This leads to the correct result, but it's not immediately obvious why that is. 

I think it'd be cleaner if we moved the code to select `AutoDiscoveryResultHeaderState` further up, assigned the result to a variable, and used the `isExpandable` property for the enable/disable decision.

```kotlin
val discoveryResultHeaderState = if (settings == null) {
    AutoDiscoveryResultHeaderState.NoSettings
} else if (settings.isTrusted) {
    AutoDiscoveryResultHeaderState.Trusted
} else {
    AutoDiscoveryResultHeaderState.Untrusted
}

Surface(
    shape = MainTheme.shapes.small,
    modifier = Modifier
        .border(
            width = 1.dp,
            color = Color.Gray.copy(alpha = 0.5f),
            shape = MainTheme.shapes.small,
        )
        .clickable(enabled = discoveryResultHeaderState.isExpandable) { expanded.value = !expanded.value },
) {
    // …
}
```

Comment (shamim-emon) [reply feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultView.kt]: @cketti Done!

**Review by cketti — APPROVED** [review]
Thanks :+1:

**Comment by davidhedlund** [comment]
> In manual mail configuration screen made the following update: 1: Turned off ripple effect upon clicking on "Configure manually" since it is not a button. 2: The removed the blue color of the text "Configure manually" so it doesn't feel like link anymore.
> 
>     * Fixes ["Configure manually" distracts users to hit the "Next" button #8512](https://github.com/thunderbird/thunderbird-android/issues/8512)

Good work!
