### PR TITLE
Fix #3529 Keyboard shotcut Z/Y swapped on Gemini QWERTZ keyboard

### LINKED ISSUE #3529: Keyboard shotcut Z/Y swapped on Gemini QWERTZ keyboard
In text editing, QWERTZ keyboard works fine, however keyboard shortcuts Y and Z are swaped.

### Expected behavior
If I press "z" button (on QW... row) a read flag should be toggled
If I press "y" button (on YXC.. row) a "copy message" function should be evoked

### Actual behavior
If I press "z" button (on QW... row) a "copy message" function is evoked
If I press "y" button (on YXC.. row) a  read flag is toggled

### Steps to reproduce
1. Switch to QWERTZ keyboard (Czech, German, ...)
2. press the Z and Y keys

### Environment
K-9 Mail version: 5.403 (from F-droid)
Android version: 7.1.1
Account type (IMAP, POP3, WebDAV/Exchange): IMAP, but irrelevant

### PR DESCRIPTION
**Pull request by schlagi123**
Fix #3529 
- change from keyCode to unicode character for different keyboard layouts

### CODE REVIEW

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt [hunk 1]
```diff
@@ -738,101 +738,126 @@ open class MessageList :
                     return true
                 }
             }
-            KeyEvent.KEYCODE_C -> {
+            KeyEvent.KEYCODE_DEL -> {
+                if (displayMode == DisplayMode.MESSAGE_LIST) {
+                    messageListFragment!!.onDelete()
+                } else if (messageViewFragment != null) {
+                    messageViewFragment!!.onDelete()
+                }
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt:746]: Can you please extract these lines to a new method named `onDeleteHotkey` or similar, and then also call this method when handling the 'd' key below. Otherwise it's too easy to miss a copy when someone wants to change how the app reacts to the delete hotkey.

**Review by cketti — CHANGES_REQUESTED** [review]

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Thanks :+1:
