### PR TITLE
Restart message list activity after display settings have been changed

### LINKED ISSUE #2136: Global display settings changes are not applied immediately
### Expected behavior
When I change some of the display settings (hiding the stars, showing the checkboxes) and go back to the current inbox, I expect the new settings to be applied to the current folder immediately.

### Actual behavior
If I am in a folder and change the global display settings and then go back to the folder, they are not applied.

### Steps to reproduce
1. Open an IMAP folder
2. Click ... > Settings > Global Settings > Display
3. Change an option, for example Hide Stars From the Message List
4. Click the back button on your phone
5. You will go back to the folder, but the stars are not hidden
6. In order to apply the settings you have to exit and folder and enter it again

### Environment
K-9 Mail version:
5.203

Android version:
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

### PR DESCRIPTION
**Pull request by starshipcoder**
Now after a user change display settings, the MessageList activity will be recreate

Fixes #2136

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for working on this :+1:

I think the approach should be changed a little bit. The settings screen shouldn't be responsible for what happens in the message list screen. Instead the message list activity should store the settings values it will use to display the UI in a data class when it is started. Then compare those stored values to the current values in ´onResume()` and restart the activity if necessary. The change shouldn't have to touch any settings screen code or the `Preferences` class.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt [hunk 1]
```diff
@@ -0,0 +1,67 @@
+package com.fsck.k9.activity
+
+import com.fsck.k9.Account
+import com.fsck.k9.FontSizes
+import com.fsck.k9.K9
+
+class MessageListActivityAppearance(accounts: List<Account>) {
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt:7]: I suggest changing this to

```kotlin
data class MessageListActivityAppearance(
    val appTheme: K9.AppTheme,
    val language: String,
    // …
    val fontSizeMessageListSubject: Int,
    // …
) {
    companion object {
        @JvmStatic
        fun create() = MessageListActivityAppearance(
            appTheme = K9.appTheme,
            language = K9.k9Language,
            // …
            fontSizeMessageListSubject = K9.fontSizes.messageListSubject,
            // …
        )
}
```

By using a data class you don't need to write the `equals()` method.

The creation could be done with default values for constructor parameters. But I like having a separate static factory method better.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+    val isChangeContactNameColor = K9.isChangeContactNameColor
+    val isShowContactPicture = K9.isShowContactPicture
+    val isColorizeMissingContactPictures = K9.isColorizeMissingContactPictures
+    val isUseBackgroundAsUnreadIndicator = K9.isUseBackgroundAsUnreadIndicator
+    val contactNameColor = K9.contactNameColor
+    val messageViewTheme = K9.messageViewTheme
+    val messageListPreviewLines = K9.messageListPreviewLines
+    val splitViewMode = K9.splitViewMode
+    val fontSizes = K9.fontSizes
+    val chipColor = accounts.map { it.chipColor }
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt:24]: There's a lot more that can change with accounts. So we need to handle this differently anyway. For now I suggest to just leave out the chipColor and concentrate on general display settings.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+        if (messageViewTheme != other.messageViewTheme) return false
+        if (messageListPreviewLines != other.messageListPreviewLines) return false
+        if (splitViewMode != other.splitViewMode) return false
+        if (chipColor != other.chipColor) return false
+        if (!areFontSizesEquals(fontSizes, other.fontSizes)) return false
+
+        return true
+    }
+
+    private fun areFontSizesEquals(fontSizes1: FontSizes, fontSizes2: FontSizes) = when {
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt:51]: `FontSizes` is a mutable class just like `Account`. It has the same lifetime, i.e. a given `Account` instance only every references the same `FontSizes` instance. So we need to copy the values, not just hold on to the reference. (See suggested code snippet above).

Right now this method will always return `true` because `fontSizes1 === fontSizes2`.

**Comment by starshipcoder** [comment]
> Thanks for working on this 👍
> 
> I think the approach should be changed a little bit. The settings screen shouldn't be responsible for what happens in the message list screen. Instead the message list activity should store the settings values it will use to display the UI in a data class when it is started. Then compare those stored values to the current values in `onResume()` and restart the activity if necessary. The change shouldn't have to touch any settings screen code or the `Preferences` class.

File: app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt (hunk 1 above)
Comment (starshipcoder) [reply app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageListActivityAppearance.kt]: Thank you for the review!

**Comment by cketti** [comment]
Thanks :+1:
