### PR TITLE
Clear folder using the MessagingController instead of on the UI thread

### LINKED ISSUE #2143: Clear local messages -> freeze
### Expected behavior
"Clear local messages" should clear the locally stored messages, allowing one to re-download the messages from the server.

### Actual behavior
Freeze.

### Steps to reproduce
1. Have a folder with some large amount of messages. A few hundred should suffice.
2. Make sure it's NOT up-to-date with the server
3. Clear its local messages.

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by philipwhiuk**
Seems to be mostly legacy that we weren't already doing it. Code was super-easy to port over.

Fixes #2143

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java [hunk 1]
```diff
@@ -3513,6 +3514,35 @@ public void run() {
...
     }
 
+    public void clearFolder(final Account account, final String folderName, final ActivityListener listener) {
+        putBackground("clearFolder", listener, new Runnable() {
+            @Override
+            public void run() {
+                LocalFolder localFolder = null;
+                try {
+                    Store localStore = account.getLocalStore();
+                    localFolder = (LocalFolder) localStore.getFolder(account.getTrashFolderName());
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java]: Why do you open the Trash folder here?

Comment (philipwhiuk) [inline k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java]: Oops, I think that was a copy and paste error 👎  bad me

**Comment by philipwhiuk** [comment]
Fixed up. Also decided to do the right thing and push some tests for it!
