### PR TITLE
handle attachments with CHILD_PART_CONTAINS_DATA data location

### LINKED ISSUE #1826: K-9 mail crashes when trying to download an attachment
I searched for a message containing a train ticket. I entered it and tried to save it. Then the app crashed.
The mail account used here was the same as in #1794 

### Environment
K-9 Mail version: 5.115
Android version: CM13

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

```
12-01 12:57:01.186 11371 11422 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
12-01 12:57:01.186 11371 11422 E AndroidRuntime: Process: com.fsck.k9, PID: 11371
12-01 12:57:01.186 11371 11422 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
12-01 12:57:01.186 11371 11422 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: Caused by: java.lang.IllegalStateException: No attachment data available
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore.getRawAttachmentInputStream(LocalStore.java:725)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore.access$100(LocalStore.java:66)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore$15.doDbWork(LocalStore.java:700)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore$15.doDbWork(LocalStore.java:684)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore.getAttachmentInputStream(LocalStore.java:684)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.provider.AttachmentProvider.getAttachmentInputStream(AttachmentProvider.java:186)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.provider.AttachmentProvider.openAttachment(AttachmentProvider.java:167)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.provider.AttachmentProvider.openFile(AttachmentProvider.java:78)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider.openAssetFile(ContentProvider.java:1374)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1554)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1620)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:419)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1107)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:664)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController.writeAttachmentToStorage(AttachmentController.java:149)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController.saveAttachmentWithUniqueFileName(AttachmentController.java:141)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController.access$900(AttachmentController.java:42)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController$SaveAttachmentAsyncTask.doInBackground(AttachmentController.java:348)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController$SaveAttachmentAsyncTask.doInBackground(AttachmentController.java:337)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	... 3 more
12-01 12:57:01.190  1350  1883 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.Search
```

### PR DESCRIPTION
**Pull request by Valodim**
There is not really a very nice way to do this because writing out the data depends on the message strucutre, which we only really have after loading the message. I opted for loading the whole message and writing it with the regular `writeTo()` routines, but also had to change the `getInputStream` logic to `writeToOutputStream`.

fixes #1826

### CODE REVIEW

File: k9mail-library/src/main/java/com/fsck/k9/mail/store/webdav/WebDavFolder.java [hunk 1]
```diff
@@ -655,7 +655,11 @@ private String generateDeleteUrl(String startUrl) {
             try {
                 ByteArrayOutputStream out;
 
-                out = new ByteArrayOutputStream(message.getSize());
+                long size = message.getSize();
+                if (size > Integer.MAX_VALUE) {
+                    size = Integer.MAX_VALUE;
```
Comment (cketti) [inline k9mail-library/src/main/java/com/fsck/k9/mail/store/webdav/WebDavFolder.java]: I'd rather throw here.

File: k9mail/src/main/java/com/fsck/k9/mailstore/LocalStore.java [hunk 2]
```diff
@@ -789,6 +789,13 @@ private static Part findPartById(Part searchRoot, long partId) {
 
             if (part instanceof LocalMessage) {
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/mailstore/LocalStore.java]: Since this can only be true for the root message you might as well move it outside the loop.

File: k9mail/src/main/java/com/fsck/k9/mailstore/LocalStore.java [hunk 3]
```diff
@@ -789,6 +789,13 @@ private static Part findPartById(Part searchRoot, long partId) {
...
                 LocalMessage localMessage = (LocalMessage) part;
+                if (localMessage.getMessagePartId() == partId) {
+                    return localMessage;
+                }
+            }
+
+            if (part instanceof LocalMimeMessage) {
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/mailstore/LocalStore.java]: You can now check for `LocalPart` instead of `LocalBodyPart` and `LocalMimeMessage`.
