### PR TITLE
Handle NIL date - per RFC3501 4.5

### LINKED ISSUE #1819: Handle 'NIL' date response
### Expected behavior
Refreshing a folder should make the server contents of that server appear in K-9

### Actual behavior
Synchronization runs for a few seconds, then aborts. The folder stays empty.

### Steps to reproduce
1. Navigate into "broken" folder
2. Swipe down
(I assume this problem depends on the IMAP server software. I'll be happy to help with testing.)

### Environment
K-9 Mail version: 5.115

Android version: 6.0.1 (CM13)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
Server Software: Zarafa 7.2.4

### Debug log
[k9-log.txt](https://github.com/k9mail/k-9/files/614218/k9-log.txt)
I removed email addresses and subject lines from all mails except the last one before the crash.

### PR DESCRIPTION
**Pull request by philipwhiuk**
Fixes #1819

### CODE REVIEW

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java [hunk 1]
```diff
@@ -11,33 +14,129 @@
 import static org.junit.Assert.fail;
 
 public class ImapListTest {
-    @Test public void testImapListMethods() throws IOException {
+
+    private ImapList buildSampleList() {
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java]: Helper methods are usually not very interesting. That's why I like to keep them at the end of the test class (out of sight).

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java [hunk 2]
```diff
@@ -11,33 +14,129 @@
...
         ImapList list = new ImapList();
         list.add("ONE");
         list.add("TWO");
         list.add("THREE");
+        return list;
+    }
+
+    @Test public void containsKey_returnsTrueForKeys() throws IOException {
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java]: Code style: annotations go on their own line

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java [hunk 3]
```diff
@@ -11,33 +14,129 @@
...
+        ImapList list = buildSampleList();
 
         assertTrue(list.containsKey("ONE"));
         assertTrue(list.containsKey("TWO"));
         assertFalse(list.containsKey("THREE"));
         assertFalse(list.containsKey("nonexistent"));
+    }
+
+    @Test public void containsKey_returnsFalseForStringThatCantBeKey() throws IOException {
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java]: Name suggestion: `containsKey_withListElementThatCannotBeKey_shouldReturnFalse`

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java [hunk 4]
```diff
@@ -11,33 +14,129 @@
...
+        return list;
+    }
+
+    @Test public void containsKey_returnsTrueForKeys() throws IOException {
+        ImapList list = buildSampleList();
 
         assertTrue(list.containsKey("ONE"));
         assertTrue(list.containsKey("TWO"));
         assertFalse(list.containsKey("THREE"));
         assertFalse(list.containsKey("nonexistent"));
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java]: I'd get rid of the negative cases (the `assertFalse()` lines). They should be separate tests (that are actually already present further down).

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java [hunk 5]
```diff
@@ -11,33 +14,129 @@
...
+    }
+
+    @Test
+    public void getKeyedValue_providesCorrespondingValues() {
+        ImapList list = buildSampleList();
 
         assertEquals("TWO", list.getKeyedValue("ONE"));
         assertEquals("THREE", list.getKeyedValue("TWO"));
         assertNull(list.getKeyedValue("THREE"));
         assertNull(list.getKeyedValue("nonexistent"));
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java]: The last two cases should probably get their own test methods.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java [hunk 6]
```diff
@@ -11,33 +14,129 @@
...
-            fail("IllegalArgumentException should have been thrown");
-        } catch (IllegalArgumentException e) { /* do nothing */ }
+    @Test
+    public void getDate_returnsCorrectDateForValidString() throws MessagingException {
+        ImapList list = new ImapList();
+        list.add("INTERNALDATE");
+        list.add("10-Mar-2000 12:02:01 GMT");
+
+        Calendar c = Calendar.getInstance();
+        c.setTime(list.getDate(1));
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapListTest.java]: This makes it hard to see what is actually tested. Suggestion:

```java
… // arrange

Date date = list.getDate(1);

Calendar calendar = Calendar.getInstance();
calendar.setTime(date);
… // assert
