### PR TITLE
Fix: EHLO SMTP parsing exceptions sound too alarming in logs

### LINKED ISSUE #9059: Make EHLO SMTP parsing exceptions that are caught sound less alarming in the logs
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

9.0

### Where did you get the app from?

Google Play

### Android version

14

### Device model

SM-S911W (Samsung Galaxy S23)

### Steps to reproduce

1. Go to Thunderbird app
2. send any email
3. open logcat apps or check adb logcat
4. See the logcat contains this EHLO parsing exception for not just one provider but multiple providers 

### Expected behavior

Correctly parses SMTP server banner lines like
```
SMTP <<< 250-disroot.org
SMTP <<< 250-PIPELINING
SMTP <<< 250-SIZE 73400320
SMTP <<< 250-ETRN
SMTP <<< 250-AUTH PLAIN LOGIN
SMTP <<< 250-AUTH=PLAIN LOGIN
SMTP <<< 250-ENHANCEDSTATUSCODES
SMTP <<< 250-8BITMIME
SMTP <<< 250 CHUNKING
```

### Actual behavior

See the logcat contains this EHLO parsing exception for not just one provider but multiple providers 
```
[04-11 16:37:18.953 1931:1969 V/SmtpTransport$logger]
Ignoring EHLO keyword line: AUTH=PLAIN LOGIN
com.fsck.k9.mail.transport.smtp.SmtpResponseParserException: EHLO keyword contains invalid character
	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.parserError(SmtpResponseParser.kt:414)
	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.checkAndNormalizeEhloKeyword(SmtpResponseParser.kt:138)
	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.parseEhloLine(SmtpResponseParser.kt:122)
	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readHelloResponse(SmtpResponseParser.kt:108)
	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendHello(SmtpTransport.kt:303)
	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:104)
	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:346)
	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:146)
	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1549)
	at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1434)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:226)
	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:166)
	at java.lang.Thread.run(Thread.java:1012)

```

### Logs

[thunderbird-logs.txt](https://github.com/user-attachments/files/19715274/thunderbird-logs.txt)

### PR DESCRIPTION
**Pull request by jasi381**
## Summary
- Remove the throwable from the `logger.log()` call when ignoring malformed EHLO keyword lines in `SmtpResponseParser`
- The informative message ("Ignoring EHLO keyword line: ...") is kept, but the alarming stack trace is no longer printed in logcat
- Update tests to reflect that `throwable` is no longer logged

Fixes #9059

## Test plan
- [x] Existing tests in `SmtpResponseParserTest.kt` updated and passing (`./gradlew :mail:protocols:smtp:test`)

### CODE REVIEW

File: mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpResponseParser.kt [hunk 1]
```diff
@@ -128,7 +128,7 @@ internal class SmtpResponseParser(
 
             keywords[keyword] = parameters
         } catch (e: SmtpResponseParserException) {
-            logger.log(e, "Ignoring EHLO keyword line: %s", ehloLine)
+            logger.log("Ignoring EHLO keyword line: %s", ehloLine)
```
Comment (wmontwe) [inline mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpResponseParser.kt]: To avoid the detekt warning, you need to change this to 

```
        } catch (_: SmtpResponseParserException) {
```
