### PR TITLE
Fix NPE in MessageCryptoHelper.addCryptoResultAnnotationToMessage()

### LINKED ISSUE #1878: Crash: NPE in MessageCryptoHelper.addCryptoResultAnnotationToMessage()
Via Play Developer Console
App version: 5.200

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65916, result=0, data=null} to activity {com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.NullPointerException: Attempt to read from field 'com.fsck.k9.mail.Part com.fsck.k9.ui.crypto.MessageCryptoHelper$CryptoPart.part' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3733)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3776)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.fsck.k9.mail.Part com.fsck.k9.ui.crypto.MessageCryptoHelper$CryptoPart.part' on a null object reference
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.addCryptoResultAnnotationToMessage(MessageCryptoHelper.java:575)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationCanceled(MessageCryptoHelper.java:558)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onActivityResult(MessageCryptoHelper.java:536)
	at com.fsck.k9.activity.MessageLoaderHelper.onActivityResult(MessageLoaderHelper.java:168)
	at com.fsck.k9.ui.messageview.MessageViewFragment.onPendingIntentResult(MessageViewFragment.java:393)
	at com.fsck.k9.activity.MessageList.onActivityResult(MessageList.java:1600)
	at android.app.Activity.dispatchActivityResult(Activity.java:6456)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3729)
	... 9 more
```

### PR DESCRIPTION
**Pull request by cketti**
Fixes #1878

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/ui/crypto/MessageCryptoHelper.java [hunk 1]
```diff
@@ -579,8 +583,17 @@ private void addCryptoResultAnnotationToMessage(CryptoResultAnnotation resultAnn
...
 
     private void onCryptoFinished() {
-        currentCryptoPart = null;
-        partsToDecryptOrVerify.removeFirst();
+        boolean currentPartIsFirstInQueue = partsToDecryptOrVerify.peekFirst() == currentCryptoPart;
+        if (!currentPartIsFirstInQueue) {
+            throw new IllegalStateException(
+                    "Trying to remove part from queue that is not the currently processed one!");
+        }
+        if (currentCryptoPart != null) {
```
Comment (philipwhiuk) [inline k9mail/src/main/java/com/fsck/k9/ui/crypto/MessageCryptoHelper.java]: Shouldn't this check be first.

If `partsToDecryptOrVerify` is empty. `peekFirst` will return null. If `currentCryptoPart` is also null we will throw. Whereas we should be logging an error.

I'm wondering if this scenario happens when the PgpApi returns two results for one part - maybe an error and a timeout response?

Comment (Valodim) [inline k9mail/src/main/java/com/fsck/k9/ui/crypto/MessageCryptoHelper.java]: If both the queue and `currentCryptoPart` are null, we don't throw but just skip (that's what happened in #1891 I hope). The check is to make sure we don't pop an element from the queue that is different from the one we have in `currentCryptoPart`, which could lead to very difficult to trace bugs down the road.

The PgpApi should never ever return more than one result, if it does we're in trouble.
