### PR TITLE
Don't use Push when the app doesn't have permission to schedule exact alarms

### LINKED ISSUE #7395: Enabling Push on Android 14 crashes v6.712
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.712

### Where did you get the app from?

Other

### Android version

Android 14

### Device model

Pixel 8 Pro

### Steps to reproduce

Open App
Wait for referesh Outlook, Google, other imap account 
Refresh takes about 5 - 10 sec
App crashes

### Expected behavior

No crash and running app

### Actual behavior

Open App
Wait for referesh Outlook, Google, other imap account 
Refresh takes about 5 - 10 sec
App crashes

### Logs

_No response_

### PR DESCRIPTION
**Pull request by cketti**
Don't try to schedule exact alarms on Android 14 when we don't have permission to do so. For a proper fix, see #7363.

Fixes #7395

### CODE REVIEW

File: backend/imap/src/main/java/com/fsck/k9/backend/imap/ImapBackendPusher.kt [hunk 1]
```diff
@@ -50,6 +50,11 @@ internal class ImapBackendPusher(
     private var currentIdleRefreshMs = 15 * 60 * 1000L
 
     override fun start() {
+        if (!idleRefreshManager.canScheduleTimers()) {
+            Timber.v("Not starting ImapBackendPusher for %s because the app can't schedule timers", accountName)
+            return
+        }
```
Comment (Goooler) [inline backend/imap/src/main/java/com/fsck/k9/backend/imap/ImapBackendPusher.kt:56]: This will stop updating folders (the logic below), Android 14 users without `SCHEDULE_EXACT_ALARM` permission will not receive new message notifications.
