### PR TITLE
fix(message-reader): complex html email rendering incorrectly

### LINKED ISSUE #3172: Wrap long lines when displaying message (text size gets too small)
K9 doesn't warp links, which makes some e-mails very wide:
screenshot_20180208-131048
***
compared to:
screenshot_20180208-131057

### PR DESCRIPTION
**Pull request by rafaeltonholo**
Fixes #3172.

This PR will address the majority of emails with complex HTML and CSS being rendered incorrectly. Large images and tables will still zoom out the WebView.

- Introduce the `:feature:mail:message:reader:api` and `:feature:mail:message:reader:impl` modules
- Adds a new feature flag "use_new_message_viewer_css_styles"
- Moved CSS styles from `DisplayHtml` to `CssStyleProvider` interface implementations, enabling old CSS fallback when the feature flag is off
- Add new CSS rules, supporting more complex email rendering for mobile

For future improvements: 
> We need to figure out a way to verify if we can resize large images and tables without using JavaScript. Otherwise, we will need to decide on either enabling JS, but limiting its usage via HTML preprocessor, or leaving it zooming out the WebView.

### CODE REVIEW

File: app-k9mail/src/main/kotlin/app/k9mail/feature/FeatureModule.kt [hunk 1]
```diff
@@ -18,4 +21,11 @@ val featureModule = module {
     includes(featureMessageListModule)
 
     single<FundingSettings> { K9FundingSettings() }
+
+    single<CssClassNameProvider> {
+        DefaultCssClassNameProvider(
+            featureFlagProvider = get(),
+            defaultNamespaceClassName = BuildConfig.APPLICATION_ID.replace(".", "-"),
```
Comment (wmontwe) [inline app-k9mail/src/main/kotlin/app/k9mail/feature/FeatureModule.kt:28]: 👍

File: app-thunderbird/src/daily/kotlin/net/thunderbird/android/featureflag/TbFeatureFlagFactory.kt [hunk 2]
```diff
@@ -25,6 +26,7 @@ class TbFeatureFlagFactory : FeatureFlagFactory {
             FeatureFlag(MessageListFeatureFlags.UseComposeForMessageListItems, enabled = false),
             FeatureFlag(MessageViewFeatureFlags.ActionExportEml, enabled = true),
             FeatureFlag(AccountSettingsFeatureFlags.EnableAvatarCustomization, enabled = false),
+            FeatureFlag(MessageViewerFeatureFlags.UseNewMessageViewerCssStyles, enabled = false),
```
Comment (wmontwe) [inline app-thunderbird/src/daily/kotlin/net/thunderbird/android/featureflag/TbFeatureFlagFactory.kt]: You could enable features that are already functionally complete for daily builds as well.

File: legacy/ui/base/src/main/java/com/fsck/k9/ui/base/KoinModule.kt [hunk 3]
```diff
@@ -13,7 +14,7 @@ val uiBaseModule = module {
             generalSettingsManager = get(),
             appCoroutineScope = get(named("AppCoroutineScope")),
         )
-    }
+    } bind net.thunderbird.core.ui.theme.api.ThemeManager::class
```
Comment (wmontwe) [inline legacy/ui/base/src/main/java/com/fsck/k9/ui/base/KoinModule.kt]: Could be an import declaration.

File: app-thunderbird/src/daily/kotlin/net/thunderbird/android/featureflag/TbFeatureFlagFactory.kt (hunk 2 above)
Comment (rafaeltonholo) [reply app-thunderbird/src/daily/kotlin/net/thunderbird/android/featureflag/TbFeatureFlagFactory.kt]: Thanks for the reminder. I've enabled it for daily builds

**Comment by Djfe** [comment]
very interesting, I will report back once this hits a release and give feedback here
Thanks for working on this!! 🙏
