### PR TITLE
Fix preview text extraction

### LINKED ISSUE #4984: Error during preview text extraction
Since the upgrade to 5.719 I have a problem, that new message are not displayed using IMAP to outlook.office365.com (where other clients do show the messages). I looks as if all messages arrived after the upgrade date are not shown. I do not see any error message, the logcat does not pint to any problem either.
I already remove all data from K9 and re-created the accounts with no success. I also de-installed the app and tried to start from scratch without success.
I am using K9 on a Samsung SM-A520F, no root, no custom ROM, Android 8.

### PR DESCRIPTION
**Pull request by cketti**
Preview text extraction failed when an empty string was used as input :see_no_evil: 

Fixes #4984

### CODE REVIEW

File: app/core/src/main/java/com/fsck/k9/message/extractors/PreviewTextExtractor.kt [hunk 1]
```diff
@@ -99,6 +98,8 @@ internal class PreviewTextExtractor {
     private val EmailSection.quoteHeaderIndex: Int
         get() {
             var quoteHeaderIndex = lastIndex
+            if (quoteHeaderIndex == -1) return -1
```
Comment (cketti) [inline app/core/src/main/java/com/fsck/k9/message/extractors/PreviewTextExtractor.kt:101]: An empty body (handled in `extractUnquotedText()`) *should* be the only way to create an empty `EmailSection`. This check is to make sure we don't crash if that assumption doesn't hold (in the future).
