### PR TITLE
Fix edge-to-edge regressions

### LINKED ISSUE #9482: Regression - Edge-to-edge support
The changes to enable edge-to-edge support caused the following regressions:

#### Fab misaligned

  Image

The Fab should hover above the bottom bar, but it's now moved up.

#### Drawer not drawn behind StatusBar

Image

The drawer should be drawn behind the StatusBar.

#### Settings not fully visible

Image

The settings list is not fully visible.

### LINKED ISSUE #9607: 12.0b6 edge-to-edge. Settings inaccessible behind android navigation buttons.
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.0b6

### Where did you get the app from?

Other

### Android version

Android 15

### Device model

Oneplus 10 Pro

### Steps to reproduce

App downloaded from GitHub.

This app version enabled edge to edge support and has resulted in some settings and buttons on multiple pages being positioned behind the android navigation buttons at the bottom of the screen. They are inaccessible as a result.

1. Account > Sending Mail : Outgoing server settings
2. Manage Folders : Bottom most folder
3. General Settings > Display : Auto-fit messages
4. Export Settings : Export Button
5. Import Settings : Import Button 
7. About > Version > change log : Show recent changes check box.
8. About : Bottom most library

Image
Image
Image
Image
Image
Image
Image

### Expected behavior

Settings and buttons are positioned above, not behind the android navigation buttons at the bottom of the screen.

### Actual behavior

Some settings and buttons on multiple pages are positioned behind the android navigation buttons at the bottom of the screen. They are inaccessible as a result

### Logs

_No response_

### LINKED ISSUE #9609: Edge-to-edge Regression - Export screen
Split from #9607.

The export button is hidden when using the 3-button navigation.

Image

### LINKED ISSUE #9610: Edge-to-edge Regression - Import Settings screen
#### Import settings > QR Code, Import button, "Please sign" text button, and Later button not visible when using 3-buttons navigation

| Import settings | Import button | "Please sign" text button, and Later button | 
| --- | --- | --- | 
| Image | Image | Image |

See also #9607

### LINKED ISSUE #9611: Edge-to-Edge regression - About screen
Split from #9607.

Needs to include a padding bottom in the content of the `fragment_about.xml`, so the whole content will be visible when scrolling all the way down while using 3-buttons navigation.

Image

### LINKED ISSUE #9612: Edge-to-edge Regression - Manage folders Screen
Split from #9607.

Needs to include a padding bottom, using the `WindowInsets` in the content of the `ManageFoldersFragment`, so the whole content will be visible when scrolling all the way down while using 3-buttons navigation.

Image

### LINKED ISSUE #9613: Edge-to-edge Regression - Changelog Screen
Split from #9607.

Needs to include a padding bottom, using the `WindowInsets` in the content of the `ChangelogFragment`, so the whole content will be visible when scrolling all the way down while using 3-buttons navigation.

Image

### PR DESCRIPTION
**Pull request by asoucar**
Fixes regressions caused by enabling edge to edge #9460 

Fixes #9607 
Fixes #9609 
Fixes #9610
Fixes #9611
Fixes #9612 
Fixes #9613 
Fixes #9482

### CODE REVIEW

**Review by wmontwe — CHANGES_REQUESTED** [review]
The mentioned issues are fixed.

I just found that on composable screens the status bar has the wrong color:

Image

Then the toolbar on XML layouts is not the right size, you could see this if looking at the text and icons in contrast to composable screens:

Portrait:



Landscape:





You could also do them as separate tickets.

**Comment by asoucar** [comment]
Fixes #9615

**Comment by asoucar** [comment]
@wmontwe I will do those last few as a new ticket

**Comment by rafaeltonholo** [comment]
> @wmontwe I will do those last few as a new ticket

Hi @asoucar, could you please create the tickets for the issues you are going to address in a separate PR? That will help to evaluate what I should review in this PR

File: legacy/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListFragment.kt [hunk 1]
```diff
@@ -333,15 +330,6 @@ class MessageListFragment :
                     typedValued,
                     true,
                 )
-                view.findViewById<ProtectionLayout>(R.id.protection_layout)
```
Comment (rafaeltonholo) [inline legacy/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListFragment.kt:336]: Could you please also remove the `<androidx.core.view.insets.ProtectionLayout />` from `message_list_fragment`? It won't have any usage after removing this line
