### PR TITLE
Test basic behaviour of executeSimpleCommand

### LINKED ISSUE #2665: IMAP Synchronization breaks when server responds with BYE after timeout.
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Synchronizing my Newsletter-Folder

### Actual behavior
Error: IOException: readStringUnti

Sometimes the App stops so that I have to stop
[k9-log4.txt](https://github.com/k9mail/k-9/files/1203039/k9-log4.txt)

it and restart.
The other folders are able to synchronize.

Log-File attached.

### Steps to reproduce
1. See appended Logfile.
2.
3.

### Environment
K-9 Mail version: 5.207

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange):

IMAP

### PR DESCRIPTION
**Pull request by philipwhiuk**
Adding a few more verification tests for `executeSimpleCommand`.

I wrote them while trying to work out the best way to fix #2665 . Still not sure on that.

### CODE REVIEW

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 1]
```diff
@@ -901,6 +901,39 @@ public void sendContinuation() throws Exception {
...
+        server.expect("4 CREATE Folder");
+        server.output("4 OK Folder created");
+
+        ImapConnection imapConnection = startServerAndCreateImapConnection(server);
+        List<ImapResponse> result = imapConnection.executeSimpleCommand("CREATE Folder");
+        assertEquals(result.size(), 1);
+
+        server.verifyConnectionStillOpen();
+        server.verifyInteractionCompleted();
+        server.shutdown();
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: `verifyInteractionCompleted()` calls `shutdown()` internally. So this line can be removed.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 2]
```diff
@@ -901,6 +901,39 @@ public void sendContinuation() throws Exception {
         server.verifyInteractionCompleted();
     }
 
+    @Test
+    public void executeSingleCommand_on_openConnection_shouldReturnResult() throws Exception {
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Why "openConnection"? I suggest the name `executeSingleCommand_withOkResponse_shouldReturnResponse`.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 3]
```diff
@@ -901,6 +901,39 @@ public void sendContinuation() throws Exception {
...
+        MockImapServer server = new MockImapServer();
+        simpleOpenDialog(server, "");
+        server.expect("4 CREATE Folder");
+        server.output("4 OK Folder created");
+
+        ImapConnection imapConnection = startServerAndCreateImapConnection(server);
+        List<ImapResponse> result = imapConnection.executeSimpleCommand("CREATE Folder");
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Nit-pick: For a strict arrange-act-assert separation this single line should be the "act" block.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 4]
```diff
@@ -901,6 +901,39 @@ public void sendContinuation() throws Exception {
...
+        assertEquals(result.size(), 1);
+
+        server.verifyConnectionStillOpen();
+        server.verifyInteractionCompleted();
+        server.shutdown();
+    }
+
+    @Test
+    public void executeSingleCommand_on_openConnection_shouldHandleFailure() throws Exception {
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Name suggestion: `executeSingleCommand_withNoResponse_shouldThrowNegativeImapResponseException`

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 5]
```diff
@@ -901,6 +901,39 @@ public void sendContinuation() throws Exception {
...
+        ImapConnection imapConnection = startServerAndCreateImapConnection(server);
+        try {
+            imapConnection.executeSimpleCommand("CREATE Folder");
+            fail("Expected exception");
+        } catch (NegativeImapResponseException e) {
+            assertEquals("Folder exists", e.getLastResponse().getString(1));
+        }
+        server.verifyConnectionStillOpen();
+        server.verifyInteractionCompleted();
+        server.shutdown();
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: `server.shutdown()` can be removed here, too.

File: k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java [hunk 6]
```diff
@@ -901,6 +901,39 @@ public void sendContinuation() throws Exception {
...
+    }
+
+    @Test
+    public void executeSingleCommand_on_openConnection_shouldHandleFailure() throws Exception {
+        MockImapServer server = new MockImapServer();
+        simpleOpenDialog(server, "");
+        server.expect("4 CREATE Folder");
+        server.output("4 NO Folder exists");
+        ImapConnection imapConnection = startServerAndCreateImapConnection(server);
+        try {
```
Comment (cketti) [inline k9mail-library/src/test/java/com/fsck/k9/mail/store/imap/ImapConnectionTest.java]: Could use empty lines to separate the "act" part.
