### PR TITLE
IMAP: Ignore errors during LOGIN fallback

### LINKED ISSUE #6744: Not prompting for new password when changed elsewhere
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.509

### Where did you get the app from?

Google Play

### Android version

12

### Device model

_No response_

### Steps to reproduce

1. have different mailboxes on k9
2. change the password of one of them outside k9 (ie web or thunderbird on windows)
3. try to access to new emails on the mailbox

### Expected behavior

realise the password has changed and prompting a request for writing a new one.

### Actual behavior

nothing, it just stops dowloading new messages without any notification or error message

### Logs

_No response_

### PR DESCRIPTION
**Pull request by cketti**
From the log in #6744 I reconstructed that the communication with the IMAP server went like this (simplified):

```text
…
C: 2 AUTHENTICATE PLAIN [credentials]
S: 2 NO AUTHENTICATE failed
C: 3 LOGIN [credentials]
S: * BYE IMAP server terminating connection
S: [server closes connection]
```

We have code to fall back to using the `LOGIN` command when `AUTHENTICATE PLAIN` fails. In this case the server closed the connection instead of sending a negative response to the `LOGIN` command. K-9 Mail treated this as an intermittent connection failure and ignored it.

This change throws the original `AuthenticationFailedException` in case the `LOGIN` command throws anything but an `AuthenticationFailedException`. This makes sure an authentication error notification will be created.

Fixes #6744

### CODE REVIEW

**Comment by cketti** [comment]
Detekt error:
> `mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:444:17:` Too many throw statements in the function saslAuthPlainWithLoginFallback. The maximum number of allowed throw statements is 2. [ThrowsCount]

Is `ThrowsCount` a useful rule? Should we disable it?

**Review by wmontwe — APPROVED** [review]
LGTM

File: mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt [hunk 1]
```diff
@@ -445,7 +449,17 @@ internal class RealImapConnection(
                 throw e
             }
 
-            login()
+            try {
```
Comment (wmontwe) [inline mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:452]: > Detekt error:
> 
> > `mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:444:17:` Too many throw statements in the function saslAuthPlainWithLoginFallback. The maximum number of allowed throw statements is 2. [ThrowsCount]
> 
> Is `ThrowsCount` a useful rule? Should we disable it?

This could be solved by adding a new `tryLogin(e: AuthenticationFailedException)` method:

```
private fun tryLogin(e: AuthenticationFailedException) = try {
        login()
    } catch (inner: AuthenticationFailedException) {
        throw inner
    } catch (inner: IOException) {
        Timber.d(inner, "LOGIN fallback failed")
        throw e
    } catch (inner: MessagingException) {
        Timber.d(inner, "LOGIN fallback failed")
        throw e
    }
```

Comment (wmontwe) [reply mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:452]: Or name it retryLogin()

Comment (cketti) [reply mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:452]: That still exceeds the ThrowsCount value of 2.

Comment (wmontwe) [reply mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:452]: Hmm, I changed it to the following and it didn't trigger for me. Also tried on a clean build.

```
    private fun saslAuthPlainWithLoginFallback(): List<ImapResponse> {
        return try {
            saslAuthPlain()
        } catch (e: AuthenticationFailedException) {
            if (!isConnected) {
                throw e
            }

            retryLogin(e)
        }
    }

    private fun retryLogin(e: AuthenticationFailedException) = try {
        login()
    } catch (inner: AuthenticationFailedException) {
        throw inner
    } catch (inner: IOException) {
        Timber.d(inner, "LOGIN fallback failed")
        throw e
    } catch (inner: MessagingException) {
        Timber.d(inner, "LOGIN fallback failed")
        throw e
    }
```

If there is still a issue, we might increase the number of allowed throws.

Comment (cketti) [reply mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:452]: Interesting. The `throw` statements are not flagged if an expression body is used for the function. They are if a block body is used (I'd like to avoid using expression bodies for functions that are multiple lines long).

I'm not sure if the `ThrowsCount` rule is useful at all. Since Kotlin doesn't support multi-catch, we might run into this quite a bit. On the other hand, if this was indeed a function where too many `throw` statements would obscure the code flow, I'm sure a couple of other detekt rules dealing with code complexity would have caught this as well.

Comment (wmontwe) [reply mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt:452]: I wouldn't disable it, as limiting throws is a good practise in Kotlin. We could instead increase the allowed count or just add `@Suppress("ThrowsCount")`.
