### PR TITLE
On removing notification, mark it's ID no longer in use

### LINKED ISSUE #1662: AssertionError: getNewNotificationId() called with no free notification ID
Crash reported via Google Play.

App version: 5.111
Android versions: 6.0, 5.1

```
java.lang.AssertionError: getNewNotificationId() called with no free notification ID
    at com.fsck.k9.notification.NotificationData.getNewNotificationId(NotificationData.java:77)
    at com.fsck.k9.notification.NotificationData.addNotificationContent(NotificationData.java:46)
    at com.fsck.k9.notification.NewMailNotifications.addNewMailNotification(NewMailNotifications.java:56)
    at com.fsck.k9.notification.NotificationController.addNewMailNotification(NotificationController.java:105)
    at com.fsck.k9.controller.MessagingController$12.messageFinished(MessagingController.java:1435)
    at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.fetch(Pop3Store.java:836)
    at com.fsck.k9.controller.MessagingController.downloadSmallMessages(MessagingController.java:1393)
    at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1196)
    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:953)
    at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
    at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
    at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
    at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
    at java.lang.Thread.run(Thread.java:818)
```

```
java.lang.AssertionError: getNewNotificationId() called with no free notification ID
    at com.fsck.k9.notification.NotificationData.getNewNotificationId(NotificationData.java:77)
    at com.fsck.k9.notification.NotificationData.addNotificationContent(NotificationData.java:46)
    at com.fsck.k9.notification.NewMailNotifications.addNewMailNotification(NewMailNotifications.java:56)
    at com.fsck.k9.notification.NotificationController.addNewMailNotification(NotificationController.java:105)
    at com.fsck.k9.controller.MessagingController$12.messageFinished(MessagingController.java:1435)
    at com.fsck.k9.mail.store.imap.ImapFolder.fetch(ImapFolder.java:770)
    at com.fsck.k9.controller.MessagingController.downloadSmallMessages(MessagingController.java:1393)
    at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1196)
    at com.fsck.k9.controller.MessagingController.access$3200(MessagingController.java:115)
    at com.fsck.k9.controller.MessagingController$40.run(MessagingController.java:4440)
    at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
    at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
    at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
    at java.lang.Thread.run(Thread.java:818)
```

```
java.lang.AssertionError: getNewNotificationId() called with no free notification ID
    at com.fsck.k9.notification.NotificationData.getNewNotificationId(NotificationData.java:77)
    at com.fsck.k9.notification.NotificationData.addNotificationContent(NotificationData.java:46)
    at com.fsck.k9.notification.NewMailNotifications.addNewMailNotification(NewMailNotifications.java:56)
    at com.fsck.k9.notification.NotificationController.addNewMailNotification(NotificationController.java:105)
    at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1571)
    at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1203)
    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:953)
    at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
    at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
    at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
    at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
    at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by philipwhiuk**
Fixes #1662

### CODE REVIEW

File: k9mail/src/test/java/com/fsck/k9/notification/NotificationDataTest.java [hunk 1]
```diff
@@ -108,6 +107,15 @@ public void testRemoveNotificationForMessageWithRecreatingNotification() throws
     }
 
     @Test
+    public void testRemoveDoesntLeakNotificationIds() {
+        for (int i = 1; i <= NotificationData.MAX_NUMBER_OF_STACKED_NOTIFICATIONS+1; i++) {
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/notification/NotificationDataTest.java]: There's some white space missing to satisfy the code style. You can avoid this in the future by importing the code style settings and using Android Studio's "Reformat code" action before committing. See https://github.com/k9mail/k-9/wiki/CodeStyle
