### PR TITLE
Generic uri parsing and fixing trailing slash issue

### LINKED ISSUE #1223: Incorrect URL detection (final slash)
### Expected behaviour

URLs automatically converted to links can include a final slash part of the URL.
### Actual behaviour

If the URL contains a final slash, the link generated ignores it, breaking some links:

```
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: 8bit

<a href="http://google.com">http://google.com</a>/<br>
```
### Steps to reproduce
1. Select HTML format in the settings
2. Send a new mail with the following content: `http://google.com`
### Environment

K-9 Mail version: 5.008

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by itiboi**
I wrote a structure for uri parsing to solve #2265 in more elegant way. To supported a new uri type, a class implementing the UriParser interface has to be created. To be applied during HTML generation, this class needs to be "registered" in HtmlConverter together with all matching uri schemes.

To fix #1223, I rewrote the parsing of http uris including support for IPv6 addresses. I created a couple tests, but of course I maybe could have missed something. So do not hesitate to comment if you notice something.

### CODE REVIEW

File: k9mail/src/main/java/com/fsck/k9/message/html/HtmlConverter.java [hunk 1]
```diff
@@ -431,23 +393,35 @@ protected static String getQuoteColor(final int level) {
...
-                }
-            } else {
-                m.appendReplacement(outputBuffer, "$0");
+        int currentPos = 0;
+        Matcher matcher = URI_SCHEME.matcher(text);
+
+        while (matcher.find(currentPos)) {
+            int startPos = matcher.start();
+
+            // Append all text in between
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/message/html/HtmlConverter.java]: We try to avoid comments because they're easily out of date when the code is changed but not the comments. It also encourages writing more readable code.

To make this more readable you could change it to

```java
String textBeforeMatch = text.substring(currentPos, startPos);
outputBuffer.append(textBeforeMatch);
```

File: k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java [hunk 2]
```diff
@@ -0,0 +1,390 @@
...
+     * @param text
+     *         Text to parse.
+     * @param startPos
+     *         First position to look at.
+     * @param authorityEnd
+     *         Position of first character which must not be part of the authority.
+     *
+     * @return Position of first character after @ sign.
+     */
+    private int matchUserInfoIfAvailable(String text, int startPos, int authorityEnd) {
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java]: This is not a public API. We don't need JavaDoc for internal methods.

File: k9mail/src/main/java/com/fsck/k9/message/html/UriParser.java [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+ */
+public interface UriParser {
+    /**
+     * Parse and linkify scheme specific uri beginning from given position. The result will be written to given buffer.
+     * @param text String to parse uri from.
+     * @param startPos Position where uri starts (first letter of scheme).
+     * @param outputBuffer Buffer where linkified variant of uri is written to.
+     * @return Index where parsed uri ends (first non-uri letter). Should be startPos or smaller if no valid uri was found.
+     */
+    int linkifyUri(final String text, int startPos, final StringBuffer outputBuffer);
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/message/html/UriParser.java]: There's no need for `final` in interfaces.

File: k9mail/src/test/java/com/fsck/k9/message/html/HtmlConverterTest.java [hunk 4]
```diff
@@ -19,7 +19,8 @@
 @Config(manifest = Config.NONE)
 public class HtmlConverterTest {
     // Useful if you want to write stuff to a file for debugging in a browser.
-    private static final boolean WRITE_TO_FILE = Boolean.parseBoolean(System.getProperty("k9.htmlConverterTest.writeToFile", "false"));
+    private static final boolean WRITE_TO_FILE =
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/message/html/HtmlConverterTest.java]: Please revert the unrelated changes in this file.

File: k9mail/src/test/java/com/fsck/k9/message/html/HtmlConverterTest.java [hunk 5]
```diff
@@ -207,4 +216,33 @@ public void testLinkifyBitcoinAndHttpUri() {
                 "http://example.com/" +
                 "</a>", outputBuffer.toString());
     }
+
+    @Test
+    public void testHttpUris() {
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/message/html/HtmlConverterTest.java]: Please only one test per test method.

**Comment by cketti** [comment]
The current code will probably also linkify the http URI in a string like `myhttp://example.org`. We probably shouldn't do that.

File: k9mail/src/main/java/com/fsck/k9/message/html/BitcoinUriParser.java [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+    @Override
+    public int linkifyUri(String text, int startPos, StringBuffer outputBuffer) {
+        Matcher matcher = BITCOIN_URI_PATTERN.matcher(text);
+
+        // Skip not matching uris
+        if (!matcher.find(startPos) || matcher.start() != startPos) {
+            return startPos;
+        }
+
+        String linkifiedUri = String.format("<a href=\"%1$s\">%1$s</a>", matcher.group());
```
Comment (itiboi) [inline k9mail/src/main/java/com/fsck/k9/message/html/BitcoinUriParser.java]: Should this be job of the UriParser or the converter?

**Comment by itiboi** [comment]
Sorry for the cody style issues, I imported the settings.jar as described. All mentioned points should be fixed.

**Comment by cketti** [comment]
I squashed all commits and cleaned up the code a bit hoping the feature was ready to merge. However, `HttpUriParser` ports one major assumption from `HttpUrl` that doesn't hold when scanning for URLs. Namely, it assumes all of the input is one URL. This leads to the code treating everything after "http://" up to the next "/" as authority. Which fails to support URLs where the authority doesn't end in a slash, e.g. the first URL in the following string will not be detected/linkified: "http://uri1.example.org some text http://uri2.example.org/path"

While trying to fix this I noticed that `HttpUriParser` supports internationalized domain names (IDN) and read up on that topic. My takeaway was "this is complicated". I think as a first step we shouldn't attempt to linkify IRIs (Internationalized Resource Identifiers), but limit ourselves to traditional URIs.

Fixing the detection of valid http URLs surrounded by text is still something that needs to be done.

**Comment by itiboi** [comment]
Thanks for taking the time. I dropped the IDN detection and allowing only simple domain names now. I also changed the parsing to a more greedy approach, now successfully detecting your example.

File: k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java [hunk 7]
```diff
@@ -18,6 +16,8 @@
 class HttpUriParser implements UriParser {
     // This string represent character group sub-delim as described in RFC 3986
     private static final String SUB_DELIM = "!$&'()*+,;=";
+    private static final Pattern DOMAIN_PATTERN =
+            Pattern.compile("\\w([\\w-]*\\w)*(\\.\\w([\\w-]*\\w)*)*(:(\\d{0,5}))?");
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java]: Unfortunately `\w` also includes the underscore which is not valid in host names.

You can use non-capturing groups by having `?:` as first characters inside the parentheses. That'll make it easier to later get to the content you do want to capture.

Example: https://github.com/itiboi/k-9/blob/cf9c3d078e6e7296f16d8d8a29905047eeeec36b/k9mail/src/main/java/com/fsck/k9/message/html/UriLinkifier.java#L17

File: k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java [hunk 8]
```diff
@@ -40,19 +40,15 @@ public int linkifyUri(String text, int startPos, StringBuffer outputBuffer) {
...
-            authorityEnd = text.length();
-        }
-
-        currentPos = matchUserInfoIfAvailable(text, currentPos, authorityEnd);
+        currentPos = matchUserInfoIfAvailable(text, currentPos);
 
-        if (!tryMatchDomainName(text, currentPos, authorityEnd) &&
-                !tryMatchIpv4Address(text, currentPos, authorityEnd, true) &&
-                !tryMatchIpv6Address(text, currentPos, authorityEnd)) {
+        int matchedAuthorityEnd = Math.max(tryMatchDomainName(text, currentPos),
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java]: The whole `Math.max()` business makes this super hard to read. There's also no need to attempt another match if one of the methods was successful. So I suggest to extract all of this to a separate method and then to check the return value after each call to `tryMatch*()` and return early if a match was found.

File: k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java [hunk 9]
```diff
@@ -79,9 +75,9 @@ public int linkifyUri(String text, int startPos, StringBuffer outputBuffer) {
         return currentPos;
     }
 
-    private int matchUserInfoIfAvailable(String text, int startPos, int authorityEnd) {
+    private int matchUserInfoIfAvailable(String text, int startPos) {
         int userInfoEnd = text.indexOf('@', startPos);
-        if (userInfoEnd != -1 && userInfoEnd < authorityEnd) {
```
Comment (cketti) [inline k9mail/src/main/java/com/fsck/k9/message/html/HttpUriParser.java]: `authorityEnd` is still a useful upper bound that can be used to avoid useless work.

**Comment by itiboi** [comment]
Thanks for the hint with `?:` and the underscore, totally forgot about that.

**Comment by cketti** [comment]
Awesome. Thanks a lot!
