### PR TITLE
Fix #5802 Import settings ignores dark theme

### LINKED ISSUE #5802: Import settings ignores dark theme
**Describe the bug**
I am unfortunately affected by the problem in #750. When K-9 lost my email accounts, I restore them on the welcome screen from my backup. After I restore the backup, K-9 uses the Light Theme, even though the Dark Theme should be applied from the backup. The Dark Theme is also visible as the current theme under General Settings, but is ignored by K-9. After switching to the Light Theme and then back to the Dark Theme, it is immediately applied.

**To Reproduce**
1. Go to 'Welcome screen'
2. Click on 'Import settings'
3. Restore the Backup containing the General settings with Dark Theme
4. K-9 will use the Light Theme
5. Go to Settings -> General Settings -> Display
6. Dark Theme is set

**Expected behavior**
K-9 should use the Dark Theme as shown in settings instead of the Light Theme.

**Screenshots**
I can provide screenshots next time #750 occurs if needed.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: 8.0.0
 - Device: Honor 8
 - Account type: doesn't matter

**Additional context**
Happens everytime #750 occurs

**Logs**

### PR DESCRIPTION
**Pull request by schlagi123**
Fix #5802

- call ThemeManager after success or partial success import
- remove calling of deprecated code

### CODE REVIEW

**Comment by cketti** [comment]
I don't want to trigger this from the UI. 

Ideally, `ThemeManager` would listen to changes to the theme setting and update automatically. `GeneralSettingsManager` + `GeneralSettings` could be used for that. However, I'm not yet sure whether to keep that approach. 
So for now I suggest calling `ThemeManager.updateAppTheme()` from `SettingsImporter`. There's already a bunch of other things that a triggered after a successful import.

**Comment by schlagi123** [comment]
Next try. I hope I use the `GeneralSettingsManager` as you expected it.

File: app/core/src/main/java/com/fsck/k9/K9.kt [hunk 1]
```diff
@@ -119,12 +119,6 @@ object K9 : EarlyInit {
...
     var k9Language = ""
 
-    @JvmStatic
-    var appTheme = AppTheme.FOLLOW_SYSTEM
-
-    var messageViewTheme = SubTheme.USE_GLOBAL
-    var messageComposeTheme = SubTheme.USE_GLOBAL
-
     @JvmStatic
     var isFixedMessageViewTheme = true
```
Comment (cketti) [inline app/core/src/main/java/com/fsck/k9/K9.kt:123]: This can be removed as well.

File: app/core/src/main/java/com/fsck/k9/preferences/RealGeneralSettingsManager.kt [hunk 2]
```diff
@@ -99,16 +100,40 @@ internal class RealGeneralSettingsManager(
...
+        getSettings().copy(messageViewTheme = subTheme).persist()
+    }
+
+    override fun setMessageComposeTheme(subTheme: SubTheme) {
+        getSettings().copy(messageComposeTheme = subTheme).persist()
+    }
+
+    override fun setFixedMessageViewTheme(fixedMessageViewTheme: Boolean) {
+        getSettings().copy(fixedMessageViewTheme = fixedMessageViewTheme).persist()
+    }
```
Comment (cketti) [inline app/core/src/main/java/com/fsck/k9/preferences/RealGeneralSettingsManager.kt:117]: Please add the `@Synchronized` annotation to these methods. Otherwise it's possible to lose updates, e.g. with the following scheduling:

```
Thread 1: getSettings()
Thread 2: getSettings()
Thread 2: copy(appTheme = …)
Thread 2: persist()
Thread 1: copy(messageViewTheme = …)
Thread 1: persist()
```

In this example the `appTheme` property is overwritten with the old value again because execution of the methods wasn't atomic.

File: app/ui/base/src/main/java/com/fsck/k9/ui/base/ThemeManager.kt [hunk 3]
```diff
@@ -5,37 +5,43 @@ import android.content.res.Configuration
...
 
 class ThemeManager(
     private val context: Context,
-    private val themeProvider: ThemeProvider
+    private val themeProvider: ThemeProvider,
+    private val generalSettingsManager: GeneralSettingsManager
 ) {
     val appTheme: Theme
-        get() = when (K9.appTheme) {
+        get() = when (generalSettingsManager.getSettings().appTheme) {
```
Comment (cketti) [inline app/ui/base/src/main/java/com/fsck/k9/ui/base/ThemeManager.kt:23]: I think this would read nicer if you extracted `generalSettingsManager.getSettings()` to a private property.

```kotlin
private val generalSettings: GeneralSettings
    get() = generalSettingsManager.getSettings()
```

File: app/ui/base/src/main/java/com/fsck/k9/ui/base/ThemeManager.kt [hunk 4]
```diff
@@ -44,11 +50,17 @@ class ThemeManager(
...
 
     fun init() {
-        updateAppTheme()
+        generalSettingsManager.getSettingsFlow()
+            .map { it.appTheme }
+            .distinctUntilChanged()
+            .onEach {
+                updateAppTheme(it)
+            }
+            .launchIn(GlobalScope)
```
Comment (cketti) [inline app/ui/base/src/main/java/com/fsck/k9/ui/base/ThemeManager.kt:59]: Instead of `GlobalScope` please use "AppCoroutineScope". See e.g. 

https://github.com/k9mail/k-9/blob/09ea6bd7e8dd5badf5eda8dbeb18ffffda15ef66/app/ui/legacy/src/main/java/com/fsck/k9/ui/changelog/ChangeLogManager.kt#L19

https://github.com/k9mail/k-9/blob/09ea6bd7e8dd5badf5eda8dbeb18ffffda15ef66/app/ui/legacy/src/main/java/com/fsck/k9/ui/changelog/KoinModule.kt#L8

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/general/GeneralSettingsDataStore.kt [hunk 5]
```diff
@@ -131,8 +131,8 @@ class GeneralSettingsDataStore(
         when (key) {
             "language" -> appLanguageManager.setAppLanguage(value)
             "theme" -> setTheme(value)
-            "message_compose_theme" -> K9.messageComposeTheme = stringToSubTheme(value)
-            "messageViewTheme" -> K9.messageViewTheme = stringToSubTheme(value)
+            "message_compose_theme" -> generalSettingsManager.setMessageComposeTheme(stringToSubTheme(value))
+            "messageViewTheme" -> generalSettingsManager.setMessageViewTheme(stringToSubTheme(value))
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/general/GeneralSettingsDataStore.kt:135]: This will save the settings twice, once via `GeneralSettingsManager` and once via `GeneralSettingsDataStore.saveSettings()`. I suggest extracting this code to separate methods and setting a boolean to skip the save operation in `GeneralSettingsDataStore`. 

Something like this:
```kotlin
private fun setMessageComposeTheme(value: String) {
    skipSaveSettings = true
    generalSettingsManager.setMessageComposeTheme(stringToSubTheme(value))
}

private fun saveSettings() {
    if (skipSaveSettings) {
        skipSaveSettings = false
    } else {
        K9.saveSettingsAsync()
    }
}
```

File: app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/import/SettingsImportFragment.kt [hunk 6]
```diff
@@ -28,6 +29,12 @@ class SettingsImportFragment : Fragment() {
     private lateinit var settingsImportAdapter: FastAdapter<ImportListItem<*>>
     private lateinit var itemAdapter: ItemAdapter<ImportListItem<*>>
 
+    private val pickDocumentReceiver = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
```
Comment (cketti) [inline app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/import/SettingsImportFragment.kt:32]: Please revert the changes to this file. They are now unrelated to the bug fix. 
If you still wish to switch to `ActivityResultContracts`, please create a new pull request for that.

**Review by cketti — CHANGES_REQUESTED** [review]
Looks good :+1: A few minor changes and this should be ready to be merged.

File: app/ui/base/src/main/java/com/fsck/k9/ui/base/ThemeManager.kt [hunk 7]
```diff
@@ -44,11 +56,17 @@ class ThemeManager(
...
 
     fun init() {
-        updateAppTheme()
+        generalSettingsManager.getSettingsFlow()
+            .map { it.appTheme }
+            .distinctUntilChanged()
+            .onEach {
+                updateAppTheme(it)
+            }
+            .launchIn(appCoroutineScope)
```
Comment (cketti) [inline app/ui/base/src/main/java/com/fsck/k9/ui/base/ThemeManager.kt:65]: During testing the app crashed. `updateAppTheme()` needs to be called from the main thread. So this line needs to be…

```suggestion
            .launchIn(appCoroutineScope + Dispatchers.Main)
```

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Thanks :heart:
