### PR TITLE
Fix search by changing the delimiter in address fields from ASCII 0 to 1

### LINKED ISSUE #5776: searching for sender name don't show results for github notifications emails
**Describe the bug**
searching for sender name don't show results for github notifications emails
( from: name < notification @ github.com > )

**To Reproduce**
1. search for a sender name of a notification mail from github

**Expected behavior**
find and show the according emails

**Screenshots**
visualization of the problem :)
---BEGIN---

----END----

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806

**Additional context**
cketti: seems to be caused by the way we store sender information combined with some unexpected behavior of sqlite

### PR DESCRIPTION
**Pull request by parkerfath**
This should fix the search so that includes the names, not just the emails, in to/from/bcc/cc/reply-to. E.g. if you were searching for an email from:

```text
cketti <notifications@github.com>
```

You could search cketti -or- github. (current app wouldn't find "cketti"

I tested this on a gmail and a non-gmail IMAP account (hosted by IONOS/1and1). Tested on local and remote. It would be my first commit on the project, though, so I'm open to feedback on what else I should test, etc.

Fixes #5776

### CODE REVIEW

File: app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+/**
+ * Write the address fields to use ASCII 1 instead of ASCII 0 as separator.
+ * Separator was previously ASCII 0 but this caused problems with LIKE and searching.
+ */
+internal class MigrationTo84(private val db: SQLiteDatabase, private val migrationsHelper: MigrationsHelper) {
+
+    fun rewriteAddresses() {
+        val addressSets = db.rawQuery(
+            "SELECT id, to_list, cc_list, bcc_list, reply_to_list, sender_list FROM messages",
```
Comment (cketti) [inline app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt:16]: We want to reduce the number of rows to update as much as possible. If you add a WHERE-clause of `WHERE empty = 0 AND deleted = 0` we skip rows we know will contain NULL in all of the address columns.

File: app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+            null
+        ).use { cursor ->
+            cursor.map {
+
+                val colVals = ArrayList<String?>(5)
+                for (i in 1..5) {
+                    colVals.add(if (it.isNull(i)) null else it.getString(i))
+                }
+                it.getLong(0) to AddressSet(colVals[0], colVals[1], colVals[2], colVals[3], colVals[4])
```
Comment (cketti) [inline app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt:25]: That works, but I think it reads nicer when written like this (also avoids the allocation of a temporary list):

```suggestion
                val messageId = it.getLong(0)

                messageId to AddressSet(
                    toList = it.getStringOrNull(1),
                    ccList = it.getStringOrNull(2),
                    bccList = it.getStringOrNull(3),
                    replyToList = it.getStringOrNull(4),
                    senderList = it.getStringOrNull(5)
                )
```

File: app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+            }.toMap()
+        }
+
+        var i = 0
```
Comment (cketti) [inline app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt:29]: This is probably an artifact of an earlier version of the code. It's unnecessary now.

File: app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+        for ((messageId, addressSet) in addressSets) {
+            rewriteAddresses(messageId, addressSet)
+            ++i
+        }
+    }
+
+    private fun rewriteAddress(inAddress: String?): String? {
+        val oldSeparator = '\u0000'
+        val newSeparator = '\u0001'
+        return inAddress?.replace(oldSeparator, newSeparator)
```
Comment (cketti) [inline app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt:39]: When using named arguments you can get rid of the variables without sacrificing readability.

```suggestion
        return inAddress?.replace(oldChar = '\u0000', newChar = '\u0001')
```

File: app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+            put("cc_list", rewriteAddress(addressSet.ccList))
+            put("bcc_list", rewriteAddress(addressSet.bccList))
+            put("reply_to_list", rewriteAddress(addressSet.replyToList))
+            put("sender_list", rewriteAddress(addressSet.senderList))
+        }
+        db.update("messages", cv, "id = ?", arrayOf(messageId.toString()))
+    }
+}
+
+private data class AddressSet(val toList: String?, val ccList: String?, val bccList: String?, val replyToList: String?, val senderList: String?)
```
Comment (cketti) [inline app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt:54]: Our maximum line length is 120. There's a quick fix in Android Studio to reformat this: Place the cursor after the opening parenthesis, press Alt+Enter (or the equivalent on your platform), then select "Put parameters on separate lines".

File: app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+import android.content.ContentValues
+import android.database.sqlite.SQLiteDatabase
+import com.fsck.k9.helper.map
+import com.fsck.k9.mailstore.MigrationsHelper
+
+/**
+ * Write the address fields to use ASCII 1 instead of ASCII 0 as separator.
+ * Separator was previously ASCII 0 but this caused problems with LIKE and searching.
+ */
+internal class MigrationTo84(private val db: SQLiteDatabase, private val migrationsHelper: MigrationsHelper) {
```
Comment (cketti) [inline app/storage/src/main/java/com/fsck/k9/storage/migrations/MigrationTo84.kt:12]: The `migrationsHelper` parameter is unused and can be removed.

**Review by cketti — COMMENTED** [review]
Very nice :+1:

A few cosmetic changes and this is good to go.

**Comment by cketti** [comment]
Thank you :heart:

Congratulations on your first contribution to K-9 Mail (and it looks like your first contribution ever to any project hosted on GitHub) :tada:

**Comment by parkerfath** [comment]
> Thank you ❤️
> 
> Congratulations on your first contribution to K-9 Mail (and it looks like your first contribution ever to any project hosted on GitHub) 🎉

Indeed! Many years professionally but first time contributing to open source. Thanks for helping me through my inaugural contribution!
