### PR TITLE
Whitelist the dir attribute to improve internationalisation

### LINKED ISSUE #3265: `dir` attribute not respected?
This is reported from someone testing our emails, so I apologize for the screenshots. 

### Expected behavior
Render order changes based on the `dir` attribute of the parent element.

### Actual behavior
Render order doesn't change.

### Steps to reproduce
1. Wrap nested content with different `dir` values:

```
<table>
  <tbody>
    <tr>
      <td dir="ltr">
        <div class="column">
          <!-- nested table -->
        </div>
        <div class="column">
          <!-- nested table -->
        </div>
     </td>
    </tr>
  </tbody>
</table>
```
should appear reversed:
```
<table>
  <tbody>
    <tr>
      <td dir="rtl">
        <div class="column">
          <!-- nested table -->
        </div>
        <div class="column">
          <!-- nested table -->
        </div>
     </td>
    </tr>
  </tbody>
</table>
```

Rendered correctly in most* clients:
image

Rendered in k9:
image

After seeing #2506 I assume this is based on an automatic interpretation of the `dir` attribute?

*Most clients = ~80 combinations on EmailOnAcid

I honestly don't know enough about this project to know whether this is inside/outside of the scope of your goals.

### PR DESCRIPTION
**Pull request by philipwhiuk**
Fixes #3265

### CODE REVIEW

File: k9mail/src/test/java/com/fsck/k9/message/html/HtmlSanitizerTest.java [hunk 1]
```diff
@@ -264,4 +264,17 @@ public void shouldKeepUris() {
...
+
+    @Test
+    public void shouldKeepDirAttribute() {
+        String html = "<html><body>" +
+                "<table><tbody><tr><td dir=\"rtl\"></td></tr></tbody></table>" +
+                "</body></html>";
+
+        Document result = htmlSanitizer.sanitize(html);
+
+        assertEquals("<html><head></head><body>" +
```
Comment (cketti) [inline k9mail/src/test/java/com/fsck/k9/message/html/HtmlSanitizerTest.java]: Wouldn't `assertEquals(html, toCompactString(result))` better communicate our expectation? (I realize the input needs to be changed then)

**Comment by philipwhiuk** [comment]
Tidied up the test. Merging.
