### PR TITLE
Disallow Addresses with `null` address part

### LINKED ISSUE #3652: Crash on open certain messages
Certain spam messages, not detected by German email provider GMX (false negative), causing k-9 to crash.

### Expected behavior
On tapping a message from folder list, the message should appear in detailed view.

### Actual behavior
On tapping a message from folder list, k-9 crashes

### Steps to reproduce
1. Try getting a spam message from GMX.
2. Account type doesn't matter.
3. Try to open the message.

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP/POP3

### Additional information
When opening the same message with Thunderbird, a blank page appears. The source view contains some crude HTML code. If needed, I can link the body's content.

Hope I hit the relevant error from **logcat**:

[logcat_10-08-2018_09-49-44.txt](https://github.com/k9mail/k-9/files/2455144/logcat_10-08-2018_09-49-44.txt)

### PR DESCRIPTION
**Pull request by wiktor-k**
This change ensures that Address objects are always created with a valid
`address` part. If an Address contains only `personal` part then it is
silently skipped from parsed list.

Unit tests have been adjusted to this new requirement.

Removed inserting Address with `null` address component introduced in
commit 68cecb168e21364b5015dea3f55b1d315f8202ae.

Fixes #3652.

This PR replaces https://github.com/k9mail/k-9/pull/3739.

See: https://github.com/k9mail/k-9/pull/3739#issuecomment-441242481

Please ensure that your pull request meets the following requirements - thanks !

* Follows our existing [codestyle](https://github.com/k9mail/k-9/wiki/CodeStyle). :white_check_mark:
* Does not break any unit tests. :white_check_mark:
* Contains a reference to the issue that it fixes. :white_check_mark:
* For cosmetic changes add one or multiple images, if possible. N/A

### CODE REVIEW

File: mail/common/src/test/java/com/fsck/k9/mail/AddressTest.java [hunk 1]
```diff
@@ -116,10 +114,7 @@ public void stringQuotationShouldCorrectlyQuote() {
 
     @Test
     public void hashCode_withoutAddress() throws Exception {
-        Address address = Address.parse("name only")[0];
-        assertNull(address.getAddress());
-        
-        address.hashCode();
+        assertEquals(0, Address.parse("name only").length);
```
Comment (cketti) [inline mail/common/src/test/java/com/fsck/k9/mail/AddressTest.java]: We try to use the arrange, act, assert pattern with one empty line between each block. In this case there's no "arrange" necessary. But we still want to separate "act" from "assert".

File: mail/common/src/main/java/com/fsck/k9/mail/Address.java [hunk 2]
```diff
@@ -46,10 +48,16 @@ public Address(String address) {
     }
 
     private Address(String address, String personal, boolean parse) {
+        if (address == null) {
+            throw new NullPointerException("address");
```
[the remark this answers is not in the document]
Comment (wiktor-k) [reply mail/common/src/main/java/com/fsck/k9/mail/Address.java]: Got it!

File: mail/common/src/test/java/com/fsck/k9/mail/AddressTest.java (hunk 1 above)
Comment (wiktor-k) [reply mail/common/src/test/java/com/fsck/k9/mail/AddressTest.java]: This has been corrected.

**Comment by wiktor-k** [comment]
I've resolved issues reported by @cketti, removed one redundant unit test and rebased this change on top of `master`. Thanks for your time!
